ofiwg/fabtests

- simple/msg.c
simple/msg.c was missed when breaking FI_COMPLETE
into separate events.
> Add missed updates from FI_COMPLETE changes

- Makefile.am
- simple/rdm_tagged_search.c
A simple RDM example that demonstrates a use case of tagged search where initially tsearch fails and after the message is sent and buffered at the receiver side, tsearch finds match with the tag.
> Added a tagged RDM example that demonstrates fi_tsearch

- Makefile.am
- simple/rdm_atomic.c
Implemented a simple example that performs some atomic operations (min, max, read, write, cswap) from each category (base atomic, fetch atomic and compare atomic) for user specified iterations and transfer sizes.
> Added RDM example that performs selected atomic operations

- simple/dgram.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_atomic.c
- simple/rdm_cntr_pingpong.c
- simple/rdm_inject_pingpong.c
- simple/rdm_multi_recv.c
- simple/rdm_pingpong.c
- simple/rdm_rma.c
- simple/rdm_tagged_pingpong.c
- simple/rdm_tagged_search.c
- simple/ud_pingpong.c
Named address vector (with a hard coded name) was being used in the examples which is not necessary and can cause problem while running multiple examples on the same machine. Since we are not using shared AV, I have removed them and fixed some minor formatting issues.
> Removed named AV from examples and fixed some formatting issues

- simple/rdm.c
Used FI_SOURCE flag and simplified the code to demonstrate one way client to server data transfer. Now the code structure matches rest of the rdm examples.
> Simplified the basic RDM example

- simple/poll.c
When we don't know what kind of completion it is, don't try to read from the cq (because it will be bogus).
@goodell please review
> simple/poll: fix trivial uninit variable

- simple/rdm_multi_recv.c
> Fix av_insert return value check for multi-recv example

- configure.ac
Add a --with-libfabric option to allow for easier use of
the fabtests on systems where libfabric is not currently
installed in the default location.  This is especially useful
for those using systems where they do not have root access.
> configure: add --with-libfabric option

- Makefile.am
- simple/rdm_rma_simple.c
We wanted to demonstrate how application specified MR key works. We did following things-
- Unset FI_PROV_MR_ATTR
- Used FI_MR_KEY and FI_MR_OFFSET flags during memory registration
- Used application specified key and offset in RMA write 
- Used FI_REMOTE_WRITE flag to get remote write completion event from remote side
> Added a simple RDM RMA example that uses application-provided MR key and offset

- simple/dgram.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_atomic.c
- simple/scalable_ep.c
- Cleaned up dgram.c code to match rdm.c code
- Added missing fi_close on av
- Removed fi_shutdown from unconnected examples
- Fixed a missing condition check on the return of av_insert call
> Cleaned up simple dgram to match simple rdm example and fixed few minor issues

- Makefile.am
- simple/dgram_waitset.c
The waitset example attaches a waitset object to multiple completion queues and uses fi_wait interface to get the signal on the waitset object to read a completion event. How to determine the corresponding completion queue the signaled waitset refers to, is an open issue (#528) for enhancement in libfabric. For now, I check all available CQs.
> Added a DGRAM example to demonstrate waitset operations

- Makefile.am
- unit/size_left_test.c
These tests are pretty simple at this point, but at some point in the
future we might be able to improve them when we expose a little more
information about queue depth via the attributes.
See https://github.com/ofiwg/libfabric/pull/525 and https://github.com/ofiwg/libfabric/issues/480
Running this particular test also requires recently filed libfabric pull requests:
* ofiwg/libfabric#525
* ofiwg/libfabric#521
* ofiwg/libfabric#518
* ofiwg/libfabric#519
> unit test for fi_tx_size_left/fi_rx_size_left funcs

- autogen.sh
- configure.ac
Remove AC_CONFIG_MACRO_DIR(config), since we didn't have any
additional macros in directory 'config'.
Check for an existing file simple/info.c instead of src/fabric.c,
which seems to be a result of copy/paste for libfabric.
Fixes issue #125.
> build fixes

- ported/libibverbs/rc_pingpong.c
- simple/imm_data.c
- simple/rdm_atomic.c
- simple/rdm_rma_simple.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_search.c
- unit/av_test.c
- unit/eq_test.c
Clang on OS X seems to be more verbose about warnings than GCC. This just fixes all of the issues it pointed out. Not sure if style is correct, but I figured I'd submit for a review. 
> Fix compilation warnings on OS X.

- include/shared.h
- simple/imm_data.c
- simple/info.c
- simple/msg.c
- simple/msg_pingpong.c
- simple/msg_rma.c
- simple/rdm_atomic.c
- simple/ud_pingpong.c
Users were getting confused by error messages that looked like this:
```shell
$ simple/fi_msg_pingpong
fi_getinfo: No such file or directory
```
The error message was referring to the C function fi_getinfo(), but there's also an fi_info Linux executable (users' eyes tend to gloss over the difference between fi_getinfo and fi_info).  This led to users getting very confused, because they thought that fi_msg_pingpong was trying to exec fi_info (which would be weird in itself), but then even though the fi_info exists and is in the user's path, it somehow wasn't being found.
Clarify the error messages to put "()" when a function is being discussed.  Technically, this probably was only relevant for the fi_getinfo() function, but I went ahead and applied it uniformly throughout the code -- just …
> fabtests: add "()" to error printfs when describing a C function

- common/shared.c
- include/shared.h
- simple/msg_pingpong.c
Also add the -f option (fabric_attr.prov_name specification), and fix the getaddr not being passed port.
This is intended for comments and review, if everything look OK I will rebase and change the other pingpong tests to use the new shared code. @shantonu @bturrubiates @a-ilango 
> Break out option parsing for client-server tests into common code.

- common/shared.c
- include/shared.h
Fix build error calling getaddr.  This call will be removed
by subsequent patches.
> Return getaddr back into the source code

- common/shared.c
- include/shared.h
- simple/dgram_waitset.c
- simple/imm_data.c
- simple/info.c
- simple/msg_pingpong.c
- simple/msg_rma.c
- simple/poll.c
- simple/rdm_atomic.c
- simple/rdm_cntr_pingpong.c
- simple/rdm_inject_pingpong.c
- simple/rdm_multi_recv.c
- simple/rdm_pingpong.c
- simple/rdm_rma.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_pingpong.c
- simple/rdm_tagged_search.c
- simple/scalable_ep.c
- simple/ud_pingpong.c
Use ft_getsrcadd(...)
Use FT_FIVERSION for global libfabric version.
Use version printing function that prints test/libfabric/api info.
@shantonu @a-ilango @jsquyres : If any of you can take a peek at these changes it would be great, they are trivial but there are a lot of them touching everything.
> Update client-server tests to use new refactored code.

- common/shared.c
- include/shared.h
- simple/dgram_waitset.c
- simple/imm_data.c
- simple/info.c
- simple/msg_pingpong.c
- simple/msg_rma.c
- simple/poll.c
- simple/rdm_atomic.c
- simple/rdm_cntr_pingpong.c
- simple/rdm_inject_pingpong.c
- simple/rdm_multi_recv.c
- simple/rdm_pingpong.c
- simple/rdm_rma.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_pingpong.c
- simple/rdm_tagged_search.c
- simple/scalable_ep.c
- simple/ud_pingpong.c
Move src==NULL check into ft_getsrcaddr.
Remove print version option from tests, add to fi_info.
Update fi_info with latest values from fabric.h
Init options with struct initializer.
> More cleanups for fabtests.

- .gitignore
Change gitignore to ignore all files under simple/ and unit/ that start with
the prefix "fi".
Master on fabtests currently has a couple of tests that were added, but 
the gitignore was not modified. If all of the binaries generated are going to
start with the prefix fi*, then use it as the ignore condition.
> Fix gitignore.

- common/shared.c
- include/shared.h
- simple/ud_pingpong.c
"&hints.src_addr" was being passed when "hints.src_addr" should have
been passed instead (no "&").
Also clean up the usage of ft_getsrcaddr for destination addresses by
adding an equivalent ft_getdestaddr routine and switching to use the
dest_addr field.
This has been broken since the overhaul to use more of the fabtests common code.
@pmmccorm please review
> fi_ud_pingpong: fix bad fi_av_insert call

- fabtests.spec.in
This allows to build the fabtests RPM against a libfabric not installed on the system. Useful for automation.
> Add --with-libfabric option to spec file.

- include/shared.h
- simple/dgram.c
- simple/dgram_waitset.c
- simple/imm_data.c
- simple/info.c
- simple/msg.c
- simple/msg_pingpong.c
- simple/msg_rma.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_atomic.c
- simple/rdm_cntr_pingpong.c
- simple/rdm_inject_pingpong.c
- simple/rdm_multi_recv.c
- simple/rdm_pingpong.c
- simple/rdm_rma.c
- simple/rdm_rma_simple.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_pingpong.c
- simple/rdm_tagged_search.c
- simple/scalable_ep.c
- simple/ud_pingpong.c
Followed @pmmccorm's re-factoring in the pingpong examples -
- Added -f option to include provider name
- Removed -d option as destination address
- Replaced printf/fpintf with FI_PRINTERR
- Added line number and casting in FR_PRINTERR
- Added missing FT_FIVERSION macro
- Mixed minor formatting issue
> Re-factored code to add -f and remove -d option

- simple/rdm_atomic.c
Fixed the code where FI_CSWAP operation was missing the iteration loop.
> Fixed the iteration issue while executing cswap atomic operation

- Makefile.am
- complex/fabtest.c
- complex/fabtest.h
- complex/ft_comm.c
- complex/ft_comp.c
- complex/ft_config.c
- complex/ft_domain.c
- complex/ft_endpoint.c
- complex/ft_msg.c
- complex/ft_test.c
Introduce a new test that will be used as a framework
to provide full coverage of the libfabric API.
The test will run as either a persistent service or
single run client app.  The client will read in a test
configuration (currently hard-coded), connect to the
server, and communicate the test parameters to the server.
The client and server will then execute the test, with
the server reporting back the results to the client.
Communication of test data is communicated over standard
TCP sockets.
The framework will be expanded to run multiple tests,
iterating over multiple variables.  It may also be
expanded to run tests using multiple threads and/or
forked processes.
---
The test currently supports the msg and tagged interfaces over all 3 …
> fabtest: Add new comprehensive test app framework

- common/shared.c
- include/shared.h
- simple/dgram_waitset.c
- simple/imm_data.c
- simple/msg_pingpong.c
- simple/msg_rma.c
- simple/poll.c
- simple/rdm_atomic.c
- simple/rdm_cntr_pingpong.c
- simple/rdm_inject_pingpong.c
- simple/rdm_multi_recv.c
- simple/rdm_pingpong.c
- simple/rdm_rma.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_pingpong.c
- simple/rdm_tagged_search.c
- simple/scalable_ep.c
- simple/ud_pingpong.c
Add an option for specifying both source and destination ports.
Pass source address info only via hints. Remove redundant code 
that did the same using fi_getinfo parameters.
If these changes are fine I'll update the other examples. I've kept the port in cs_opts so that it doesn't break other examples for now.
This should fix #130 .
@shantonu @jithinjosepkl Let me know if these look good.
> simple: Add source and destination port options + cleanup

- common/shared.c
- complex/fabtest.c
- complex/ft_comm.c
- complex/ft_comp.c
- complex/ft_domain.c
- complex/ft_endpoint.c
- complex/ft_msg.c
- include/shared.h
- simple/dgram.c
- simple/dgram_waitset.c
- simple/imm_data.c
- simple/info.c
- simple/msg.c
- simple/msg_pingpong.c
- simple/msg_rma.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_atomic.c
- simple/rdm_cntr_pingpong.c
- simple/rdm_inject_pingpong.c
- simple/rdm_multi_recv.c
- simple/rdm_pingpong.c
- simple/rdm_rma.c
- simple/rdm_rma_simple.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_pingpong.c
- simple/rdm_tagged_search.c
- simple/scalable_ep.c
- simple/ud_pingpong.c
Replaced the FI_* macros defined in include/shared.h as suggested by @shefty so that FI_* is reserved for libfabric specific things. 
FI_STR_LEN  -> FT_STR_LEN
FI_DEBUG -> FT_DEBUG
FI_PRINTERR -> FT_PRINTERR
> Replaced FI_* macros with FT_* macros

- Makefile.am
- configure.ac
Fabtests are behind the libfabric release cycle, but tag a 1.0.0 alpha release, so that people downloading the libfabric release candidates have something that they can run against the library and providers.
> 1.0.0-alpha release

- complex/ft_comp.c
The function was returning 0 always.
gcc-4.9.1 generated a warning.
> complex/ft_comp: return correct value

- common/shared.c
- include/shared.h
- simple/msg_rma.c
- simple/rdm_rma.c
Add a command-line option to support using the writedata operation to
send remote CQ data to the simple/fi_msg_rma and simple/fi_rdm_rma
tools.
We test that provider gives a sensible context value on the remote CQ
data completion.  The two sensible values are NULL (meaning that the
remote CQ data did not consume a recv WQE) or the context value of the
next queued fi_recv* (meaning that the remote CQ data consumed a recv
WQE).  We also test that the completion data is correctly transferred.
We add an enum to specify the RMA operation type, which allows us to
cleanly add writedata to the set of operations supported by the RMA
tests (since libfabric itself doesn't supply a constant that can be
cleanly used for this purpose).
Signed-off-by: Patrick MacArthur <pmacarth@iol.unh.edu>
> Add writedata support to RMA examples

- simple/rdm_atomic.c
simple/rdm_atomic example always runs for all message sizes and 100k iterations as run_all_sizes=1 by default.
- removed run_all_sizes variable and reused opts.custom variable to determine if user has specified custom message size and iteration
> Fixed custom iteration issue and removed redundant variable.

- simple/msg_rma.c
- simple/rdm_rma.c
This caused my (informal) continuous integration test builds to fail
because they run 'make CFLAGS="-g -O2 -Werror"'.
> fix missing assert.h includes

- complex/fabtest.c
- ported/libibverbs/rc_pingpong.c
- ported/librdmacm/cmatose.c
- simple/cq_data.c
- simple/dgram.c
- simple/dgram_waitset.c
- simple/info.c
- simple/msg.c
- simple/msg_pingpong.c
- simple/msg_rma.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_atomic.c
- simple/rdm_cntr_pingpong.c
- simple/rdm_inject_pingpong.c
- simple/rdm_multi_recv.c
- simple/rdm_pingpong.c
- simple/rdm_rma.c
- simple/rdm_rma_simple.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_pingpong.c
- simple/rdm_tagged_search.c
- simple/scalable_ep.c
- simple/ud_pingpong.c
- unit/av_test.c
- unit/eq_test.c
- unit/size_left_test.c
Allocate hints using fi_allocinfo, and reference the new
location of the ep_type field.
> Use ep_type from ep_attr, rather than fi_info

- Makefile.am
- unit/dom_test.c
This small, simple test shows a big problem with the
PSM provider.  I'd like to know if this is considered
correct behavior, I certainly hope not since it will
otherwise make it very difficult to use the psm provider
in layered software.
Basically the test creates a fabric handle, and then
tries to open one or more domains using that handle.
The sockets provider works fine with multiple domains
being created from a fabric handle.  Likewise for a
provider I'm working on.
In contrast, the PSM provider returns the following
error if more one tries to create more than one domain:
bash-4.1$ ./fi_dom_test -f psm -n 2
fi_domain num 1 Device or resource busy
Signed-off-by: Howard Pritchard <howardp@lanl.gov>
> fabtests/unit: add a simple domain obj test

- common/shared.c
- Check if hints->fabric_attr and hints->domain_attr are already allocated.
- Copy optarg when filling domain_attr->name and fabric_attr->prov_name
to prevent invalid free by fi_freeinfo().
> common/shared: Fix memory leaks and prevent invalid free.

- unit/av_test.c
The return from fi_allocinfo struct wasn't
being checked correctly.
@shefty 
Signed-off-by: Howard Pritchard <hppritcha@gmail.com>
> univ/av_test: fix minor bug in test

- unit/eq_test.c
Addressed EQ test failures based on libfabric man pages
- The return value of fi_eq_read should be 0 when eq is empty
- Both -EAGIAN and write-success should be allowed return value when EQ write overflow is tested. A provider can choose to buffer writes since the man page says the size attribute specifies the "minimum" size of the eq.
This fixes test failures.
> Fixed fi_eq_read/write test issues when eq is empty/full

- simple/ud_pingpong.c
Check to ensure that handles are non-NULL before invoking operations on them during shutdown.  This prevents segv's when the test fails very early / before everything is setup properly.
> ud_pingpong: ensure things are setup before taking them down

- simple/dgram.c
- simple/rdm.c
- simple/rdm_rma_simple.c
- unit/av_test.c
- unit/eq_test.c
- unit/size_left_test.c
Strings from optarg can't be freed. This causes a seg fault in fi_freeinfo.
Wrap all string assignments using optarg with strdup.
> Fix segfault in fi_freeinfo.

- simple/cq_data.c
- simple/msg.c
- simple/msg_pingpong.c
- simple/msg_rma.c
For tests where the fi_reject method was invoked
during processing of connection requests, the
info object was not being handled properly.  This results in
random segfaults within the sockets provider.
Initializing the info pointer correctly in the tests
eliminates segfaults.
@shefty 
Signed-off-by: Howard Pritchard <howardp@lanl.gov>
> fabtests/simple:fix prob with use of fi_reject

- simple/rdm_rma.c
If not compiled with asserts enabled, an invalid op_type would fall
through to fi_mr_reg() with an uninitialized access_mode.
> simple/rdm_rma.c: fix compiler warning

- unit/eq_test.c
This is a partial revert of daba27cfa2afbacad2b1f6c5b9f2f49a008e54d3.
See discussion at ofiwg/libfabric#738 for reasoning behind this change.
> eq_test: expect -FI_EAGAIN from empty EQ read

- common/shared.c
- complex/ft_test.c
- include/shared.h
- ported/libibverbs/rc_pingpong.c
- ported/librdmacm/cmatose.c
- scripts/ft_runall
- simple/cq_data.c
- simple/dgram.c
- simple/dgram_waitset.c
- simple/msg.c
- simple/msg_pingpong.c
- simple/msg_rma.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_atomic.c
- simple/rdm_cntr_pingpong.c
- simple/rdm_inject_pingpong.c
- simple/rdm_multi_recv.c
- simple/rdm_pingpong.c
- simple/rdm_rma.c
- simple/rdm_rma_simple.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_pingpong.c
- simple/rdm_tagged_search.c
- simple/scalable_ep.c
- simple/ud_pingpong.c
- unit/dom_test.c
This PR is based on @shefty 's PR on synchronization issue:
- Fixed missing FI_REMOTE_COMPLETE flag for simple tests
- Added missing posting buffer required for ft_finalize call before closing ep
- Added missing stdup for string assignment
- Corrected function call for machine readable print
> Pr/fabtest: Fix for latest libfabric on 32 bit systems

- complex/fabtest.h
- complex/ft_comp.c
- complex/ft_config.c
- complex/ft_msg.c
- complex/ft_test.c
- scripts/ft_runall
Update to support the AV as part of domain attribute and handle datagram retries
> Fix fabtest to run over sockets provider in virtual linux

- Makefile.am
- common/osx/osd.c
- configure.ac
- include/osx/osd.h
- include/shared.h
- ported/librdmacm/cmatose.c
I never submitted the OS X fix for fabtests. It's simpler and only requires adding a clock_gettime implementation for OS X. I copied the same solution.
@shefty cmatose.c includes byteswap.h and I couldn't see a reason for that. I removed it and it isn't generating any warnings/errors on OS X or Linux. Git blame says that you added that include statement. Is it still necessary? 
@jsquyres Could you check my configury? 
> Fix OS X build.

- common/shared.c
- ported/libibverbs/rc_pingpong.c
- ported/librdmacm/cmatose.c
- simple/cq_data.c
- simple/dgram.c
- simple/dgram_waitset.c
- simple/msg.c
- simple/msg_pingpong.c
- simple/msg_rma.c
- simple/rdm.c
- simple/rdm_inject_pingpong.c
- simple/rdm_multi_recv.c
- simple/rdm_pingpong.c
- simple/rdm_rma.c
- simple/rdm_tagged_pingpong.c
- simple/rdm_tagged_search.c
- simple/ud_pingpong.c
- unit/eq_test.c
- Allowed wait_for_completion to continue when fi_cq/eq_read returns -FI_EAGAIN
- Fixed the loop issue which was based on "0" return value from fi_cq/eq_read 
- Fixed a missing -f option in option list for ported/librdmacm/cmatose
Fixes #192 @patrickmacarthur @bturrubiates @jithinjosepkl, can you please review?
> Fixed fabtests issues with the change of cq/eq_read return value

- simple/msg_rma.c
- simple/rdm_rma.c
FI_REMOTE_CQ_DATA is removed from capability. RMA tests are updated to match the latest libfabric.
> Removed FI_REMOTE_CQ_DATA flag from capability as per libfabric change

- Makefile.am
- simple/msg_epoll.c
This example (modified slightly from msg.c) demonstrates what I believe to be a problem in the verbs provider `fi_cq_sread` implementation.  Waiting on an epoll fd that has the rcq wait obj never wakes in the verbs case, works fine for e.g. sockets.
> fabtests/simple: add epoll-based cq wait object example

- ported/librdmacm/cmatose.c
- 7471 is used by Apple QuickTime Streaming Server, causing
the test to fail on Mac
> Use different port for cmatose

- scripts/runFabtests.sh
A simple script to run all the fabtests with use specified provider and server/client address. It would be useful to perform a quick validation before submitting a PR. Contributed by @pmmccorm and @a-ilango.
Usage:
<code>
./scripts/runFabtests.sh test_bin_path provider_name all|quick server_addr client_addr
./scripts/runFabtests.sh /path/to/fabtests/install/dir/bin sockets all 127.0.0.1 127.0.0.1
</code>
This will run all the fabtests on sockets provider looping back on localhost. Currently, the script ssh'es to client and server to run the tests. So, those nodes need to be added to authorized hosts list. I have created an issue for the improvement of the script we can do later #207.
> Added a script to run all fabtests on user specified provider and nodes

- Makefile.am
- configure.ac
Don't build the simple/fi_msg_epoll test if we don't have it.
Fixes #211 
@jithinjosepkl please verify
> tests: check for epoll_create1()

- scripts/runFabtests.sh
- simple/dgram_waitset.c
- simple/rdm_rma_simple.c
- unit/size_left_test.c
- Fixed runFabtests.sh script to be consistent with #200. Added a missing unit test and adjusted timeout value for quick validation.
- Fixed the missing unit test. It was using av but taking the default ep_type which was MSG. Changed it to use RDM
- Added missing initialization for options
"Signed-off-by: Shantonu Hossain <shantonu.hossain@intel.com>"
> Fixes for fabtests to be consistent with latest commit

- pingpong/ud_pingpong.c
- ported/libibverbs/rc_pingpong.c
- ported/librdmacm/cmatose.c
- scripts/runFabtests.sh
- simple/msg_epoll.c
- streaming/rdm_multi_recv.c
- unit/av_test.c
- unit/dom_test.c
- unit/eq_test.c
- unit/size_left_test.c
Make output yaml-parsable.
Add -v switch to see output when test fails.
Check if test is not supported (return FI-ENODATA) and skip (vs fail).
Clean up more correct and quiet.
Output now looks like this without the verbose switch:
```
fi_av_test -d 192.168.10.1 -n 1 -f usnic:               Fail
fi_dom_test -n 2 -f usnic:                              Fail
fi_eq_test -f usnic:                                    Fail
fi_size_left_test -f usnic:                             Fail
fi_cq_data -f usnic:                                  Notrun
fi_dgram -f usnic:                                    Notrun
fi_dgram_waitset -f usnic:                            Notrun
fi_msg -f usnic:                                      Notrun
fi_msg_epoll -f usnic:                                  Fail
fi_poll -f …
```
> Update fabtests.sh script and add features.

- Makefile.am
Using dist prefix for bin_SCRIPTS would make scripts built as part of make dist.
> Fix RPM build errors.

- scripts/runfabtests.sh
Make path argument optional, and use $PATH when not specified.
Specifying more -v's prints failed/notrun test output for debugging.
Which test-set to run is now optional, defaulting to 'all'.
Break tests into more categories and allow to be specified.
```
./scripts/runfabtests.sh -h
Usage: ./scripts/runfabtests.sh [-vtp] <provider_name> <server_addr> <client_addr>
[-vtp] verbose
[-t] test type(s): all,quick,unit,simple
[-p] path to test bins (default PATH)
```
Example invocations:
```
$ runfabtests.sh sockets host1 host2
$ runfabtests.sh -t unit -p $CWD/unit psm host1 host2
$ runfabtests.sh -t quick,unit sockets host1 host2
```
> More features for runfabtests.sh.

- common/shared.c
- simple/cq_data.c
- simple/rdm_rma_simple.c
- streaming/msg_rma.c
- streaming/rdm_rma.c
simple/cq_data: Pass correct modes in hints and use FD wait obj for CQ (for using sread).
other fixes: fix typo and use FT_ERR
> simple: pass correct modes and use FD wait obj for CQ

- simple/scalable_ep.c
- Pass rx/tx attr as NULL in scalable-ep example, instead of passing them uninitialized.
> Fix uninitialized tx/rx attr in scalable-ep example

- simple/rdm_tagged_peek.c
- fixed wait_for_tagged_completion call rcq instead of scq.
- removed extra recv_msg call since tagged_peek does the same thing.
> Fixed hang issue in simple/rdm_tagged_peek

- scripts/runfabtests.sh
Without this change, the "good address" is simply hard-coded into the
runfabtests.sh script, which is likely to not work on any generic
test cluster without source code modification.
> runfabtests.sh: add -g GOOD_ADDR option

- simple/poll.c
This example was parsing the address options. Updated it to use the common code.
> simple/poll: Make use of common code for address options.

- simple/poll.c
The usnic provider returns -FI_ENOSYS for several of these fi_poll
operations, which was triggering the cleanup logic.  The cleanup logic
would SEGV in at least two places as it was written.
> fi_poll: fix bad cleanup logic

- scripts/runfabtests.sh
If zsh is used as the default shell and the user has `setopt extendedglob`
in their settings, this `grep` command will generate some
very different output than expected, breaking the rest of the pipeline.
The "^" is the problem in this particular instance.  Single quoting the
argument fixes the issue.
Also, kill the incorrect redirection to /dev/null.  That pipeline
shouldn't be generating stdout messages anyway, and we probably *do*
want to see stderr messages (that's how I found this issue).
> runfabtests.sh: quote grep args for zsh

- pingpong/ud_pingpong.c
The src_addr returned in fi_info may not have a source port
set.  Use fi_getname after the endpoint is allocated to get
the fully assigned address.
> ud_pingpong: Use fi_getname to retrieve src_addr

- streaming/rdm_atomic.c
Base atomic operations no longer includes FI_ATOMIC_READ. So removed it from the test.
@jithinjosepkl, can you please check?
> streaming/rdm_atomic: Removed FI_ATOMIC_READ from base atomic op

- complex/fabtest.h
- complex/ft_config.c
- complex/ft_endpoint.c
- complex/ft_msg.c
- complex/ft_test.c
The UD data streaming test will hang if packets are lost.
Update the test to work if this occurs, which is likely
when running over true datagrams.
> fabtest: Fix unconnected bandwidth tests

- complex/fabtest.c
- complex/fabtest.h
- complex/ft_config.c
- complex/ft_domain.c
- complex/ft_test.c
* Add a test set for verbs provider
* Add server timeout when waiting for incoming connection request from client.
* Fix race condition in fabtest when run over verbs
* Show provider info in results and reset current test type index to 0 after iterating though all types.
> complex/fabtest: add verbs test set + bug fixes

- pingpong/ud_pingpong.c
When we free it, set it to NULL so that later error recovery doesn't try to free it again.  Otherwise, a bogus command line like this can cause a segv:
./pingpong/fi_ud_pingpong 30.0.11.42 -s 999
@goodell Please review
> ud_pingpong.c: prevent segv on user CLI error

- scripts/runfabtests.sh
- unit/av_test.c
Also specify that argument in `runfabtests.sh`
This fixes the case when we want to run tests between interfaces which
are not the first items returned by libfabric's `fi_getinfo` call.
> fi_av_test: allow a src addr to be specified

- Makefile.am
- scripts/rft_yaml_to_junit_xml
- scripts/runfabtests.sh
Jenkins and other testing/CI tools can parse jUnit XML files to display
summaries of testing results.
@jsquyres please review
> runfabtests.sh: add jUnit XML output option (-x)

- scripts/runfabtests.sh
I didn't see this until I ran with the sockets provider.  See also
ofiwg/fabtests#259.
> runfabtests: small fix for time formatting

- simple/msg.c
Otherwise we aren't respecting the "-s" parameter to the test.
> fi_msg: pass the src_addr on the server side too

- scripts/runfabtests.sh
A few minor/trivial cleanups on runfabtests.sh, and the addition of the "-e" option to allow you to skip tests (e.g., if you know they're going to fail).
> runfabtests exclusions

- common/shared.c
- include/shared.h
- pingpong/msg_pingpong.c
- ported/libibverbs/rc_pingpong.c
- ported/librdmacm/cmatose.c
- simple/cq_data.c
- simple/msg.c
- simple/msg_epoll.c
- streaming/msg_rma.c
* Add eq_readerr common function.
* In cq_readerr, exit if fi_cq_readerr fails. Print error string.
* Update examples to make use of eq_readerr
> EQ and CQ readerr additions + fixes

- complex/fabtest.c
- complex/fabtest.h
- complex/ft_config.c
By default, the node and service options given in test config would be used.
If it is not present user provided node and service options would be used.
> complex: Add options to get destination address and port from command line

- common/osx/osd.c
- include/osx/osd.h
We emulate `clock_gettime()` on OS X.  However, according to http://stackoverflow.com/a/21352348/1120009, `host_get_clock_service()` should not be used -- it's inaccurate and slow.
This PR updates the `clock_gettime` emulation on OS X to use `gettimeofday()` instead.
It also makes a minor tweak to `osx/osd.h`, and adds support for emulating `CLOCK_REALTIME_COARSE` (in anticipation of PR #269).
@bturrubiates Please review.
> Use gettimeofday() on OS X

- pingpong/ud_pingpong.c
- scripts/runfabtests.sh
Since fi_ud_pingpong is a simple UD pingpong test, it has no retrans functionality.  Hence, if there's even a single drop, the test will hang (this causes Cisco's internal Jenkins' tests to arbitrarily "fail").
Instead, if any individual receive goes longer than [timeout] seconds, just quit the test and return the runfabtests.sh-understood 61 exit status to indicate that the test was skipped.
[ ***EDIT the original version of this PR returned value 77, not 61*** ]
@goodell Per our discussion yesterday, please review this.
> Add a timeout to fi_ud_pingpong test

- scripts/runfabtests.sh
Hitting extraneous input during runfabtests runs could cause the ssh'ed cleanup commands to get confused and hang (and eventually be killed by "timeout").  Instead, force the ssh's to tie /dev/null to stdin via the -n parameter.
> runfabtests: force ssh to get /dev/null as stdin

- pingpong/ud_pingpong.c
As pointed out in #273, the calculation is backwards.
> ud_pingpong: fix the timeout (i.e., "now - past")

- include/shared.h
Make it clear that the first number is a line number by also printing the filename, and put "ret=%d" for the return value output.
> shared.h: make the FI_PRINTERR message more clear

- pingpong/ud_pingpong.c
- Don't exit with a negative value; just exit FI_ENODATA (i.e., 61) that runfabtests.sh understands
- Since we're not propagating -FI_ENODATA up the stack any more, the final ret frob is no longer necessary.
@bturrubiates please review
> fi_ud_pingpong: more UD timeout fixes

- pingpong/ud_pingpong.c
The size of the buffer is equal to the lesser of `opts.transfer_size` and `max_msg_size` (MTU). The current code allows the buffer to be limited to the `max_msg_size` if it is smaller than `opts.transfer_size` but will still attempt to send a message of size `opts.transfer_size`. 
This fix skips over test cases where the transfer size is larger than the buffer size (MTU). I'm not sure how to define the error case behavior. It makes sense to skip the test cases when doing the built in set of test cases, but should an error message be given when a transfer size specified with `-S` is larger than the MTU?
@shefty @goodell @jsquyres 
> Don't allow fi_ud_pingpong to make sends larger than the buffer_size

- man/fabtests.7.md
- scripts/runfabtests.sh
Removed the reference of fi_info test from runfabtests and man page as a followup of #282 
> Removed fi_info's reference from runfabtests and man page

- pingpong/rdm_cntr_pingpong.c
- pingpong/rdm_inject_pingpong.c
- pingpong/rdm_pingpong.c
- pingpong/rdm_tagged_pingpong.c
- pingpong/ud_pingpong.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
ft_read_addr_opts is a function used by a lot of the fabtests.
These tests were replicating the function and not calling it.
> use ft_read_addr_opts when possible

- streaming/rdm_atomic.c
If fi_send is failed, rdm_atomic was still waiting for completion. Added a return to gracefully exit.
> Returned error if fi_send fails

- pingpong/ud_pingpong.c
There is no need for this test to specify the address
format. The test doesn't interpret addresses, and not
specifying the address format makes the test more portable.
> ud_pingpong: remove addr_format specification

- pingpong/ud_pingpong.c
Test should use fi->dest_addr, obtained in common_setup
not hints->dest_addr.
Minor cleanup of unused label err1.
Extracted from PR #271
> ud_pingpong: use the right dest_addr in av_insert

- pingpong/ud_pingpong.c
Function common_setup() frees resources when returning failure. But the
calling function server_connect() tries to double free the resources
upon failure.
Signed-off-by: Xuyang Wang <xuywang@cisco.com>
> Fixed a double-free bug in server setup error handling path

- complex/fabtest.h
- complex/ft_main.c
- include/shared.h
- ported/libibverbs/rc_pingpong.c
- unit/av_test.c
- unit/dom_test.c
- unit/eq_test.c
- unit/size_left_test.c
The 1.1 release doesn't change anything used by fabtests.
> Update fabtests to support libfabric 1.1

- pingpong/ud_pingpong.c
As per ofiwg/libfabric#1140 the send/recv functions should take a length that includes the prefix length. Also include a command line switch to enable prefix mode. This makes the test non-prefix mode by default as opposed to prefix mode as it was before. The only provider this affects is the usnic provider.
This is analogous to ofiwg/libfabric#1143.
@goodell @jsquyres @shefty
> ud_pingpong.c: Update send buffer length to comply with API

- common/shared.c
- include/shared.h
- pingpong/msg_pingpong.c
- pingpong/rdm_inject_pingpong.c
- pingpong/rdm_pingpong.c
- pingpong/rdm_tagged_pingpong.c
- pingpong/ud_pingpong.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_peek.c
- simple/scalable_ep.c
- streaming/msg_rma.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
Without this ud_pingpong could SEGV at ft_finalize time or report
truncation errors.
> ft_finalize: respect FI_MSG_PREFIX if selected

- common/shared.c
- include/shared.h
- pingpong/msg_pingpong.c
- pingpong/rdm_inject_pingpong.c
- pingpong/rdm_pingpong.c
- pingpong/rdm_tagged_pingpong.c
- pingpong/ud_pingpong.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_peek.c
- simple/scalable_ep.c
- streaming/msg_rma.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
This reverts commit a9c3643142b1368664db7341cb586790a4d7dd63.
Without this ud_pingpong could SEGV at ft_finalize time or report
truncation errors.
> Revert "ft_finalize: respect FI_MSG_PREFIX if selected"

- scripts/runfabtests.sh
Enables testing of prefix mode using jenkins. Providers who do not support prefix mode should still pass.
@goodell @shefty 
> runfabtests.sh: Add prefix version of fi_ud_pingpong to standard suite.

- scripts/runfabtests.sh
Fixes issue where test names that are a substring of an excluded test name get excluded.
Changed to `test_exe` since it includes the `fi` prefix. In the function `$1` will only expand to the first part of `test_exe` which is `fi_test`. 
Example:
```bash
$ EXCLUDE="fi_cq_data,fi_dgram_waitset,fi_msg_poll,fi_poll,fi_cmatose,fi_rdm_cntr_pingpong"
$ function old_is_excluded {
>   local e=$(echo $EXCLUDE | sed -e s/$1//)
>   if [[ "$EXCLUDE" != "$e" ]]; then
>     echo 1
>   else
>     echo 0
>   fi
>   return
> }
$ function new_is_excluded {
>   local i
>   for i in $(echo "$EXCLUDE" | tr -s "," " "); do
>     if [[ "$i" = "$1" ]]; then
>       echo 1
>       return
>     fi
>   done
>   echo 0
> }
$ old_is_excluded fi_dgram
1
$ new_is_excluded fi_dgram
0
$ old_is_excluded fi_dgram_waitset
1 …
```
> runfabtests.sh: Fix is_excluded function to only match full test names.

- Makefile.am
- man/fabtests.7.md
- scripts/runfabtests.sh
- simple/msg_sockets.c
This test verifies that using fi_setname() on a passive endpoint and transforming the passive endpoint into an active one on the client side works correctly.  This functionality is required by UNH EXS and rsockets.
I am open to suggestions on how to better integrate this into fabtests, but having had multiple provider maintainers use this test, I would like to get something to test this particular functionality into fabtests proper.
This has been tested against ofiwg/libfabric#1160 and contains the fix that @a-ilango requested in that PR.
> [RFC] Add new test: fi_msg_sockets

- AUTHORS
- COPYING
- Makefile.am
- common/jsmn.c
- complex/ft_config.c
- complex/ft_test_config.json
- include/jsmn.h
- include/shared.h
This patch adds support for complex/fi_ubertest to read test configuration
from a file. The configuration should be in JSON format. An example
config file is also added.
> complex/fi_ubertest: Add support for config files.

- scripts/runfabtests.sh
This fixes an issue that was introduced in PR #304.
The msg_sockets tool requires that the -s option is specified even on
the client side, since it tests the functionality of `fi_setname`.
This was forgotten when the test was added to runfabtests.sh in commit
ae3d7e6c8341ae51264111bcb5bf7190e9bc73a8.
Signed-off-by: Patrick MacArthur <pmacarth@iol.unh.edu>
> scripts/runfabtests.sh: Pass -s option to msg_sockets

- simple/msg_sockets.c
This fixes an issue reported by @hppritcha in https://github.com/ofiwg/fabtests/commit/ae3d7e6c8341ae51264111bcb5bf7190e9bc73a8#commitcomment-12448399.
Since fabtests needs to work on an IB-less system, and AF_IB is not yet
supported by the verbs provider, just remove the AF_IB support in the
test for now.  It can be added back in a more robust way once the verbs
provider gains support for AF_IB addresses.
Signed-off-by: Patrick MacArthur <pmacarth@iol.unh.edu>
> simple/msg_sockets: Remove infiniband/ib.h include

- pingpong/ud_pingpong.c
If fi_ud_pingpong server is started and client is not started within 5s, it prints:
server connect timeout(): ret=-11 (Resource temporarily unavailable)
- Modified error log to explain the timeout error
- Changed default timeout from 5s to 30s
Suggested by @rfaucett. Please check if its alright.
> Modified error log to explain timeout error

- common/shared.c
Make a copy of the passed-in hints and pass that copy down to fi_getinfo() when resolving addresses.  The hints contain user-specified details already (e.g., "-f providername"), and that should be preserved when calling fi_getinfo().
Otherwise, other providers get activated (and can emit warning messages).
> shared.c: pass hints when calling fi_getinfo()

- pingpong/ud_pingpong.c
This option is not supported on SLES11 SP4 and results in
a build error.  Replace with CLOCK_MONOTONIC to match all
other use cases.
> Replace use of CLOCK_REALTIME_COARSE

- simple/msg_sockets.c
In order to support loopback testing, the client needs to
use a different source port than the server.
> fi_msg_socket: Use different src port for client

- common/shared.c
- complex/ft_domain.c
- include/shared.h
- pingpong/msg_pingpong.c
- pingpong/rdm_cntr_pingpong.c
- pingpong/rdm_inject_pingpong.c
- pingpong/rdm_pingpong.c
- pingpong/rdm_tagged_pingpong.c
- pingpong/ud_pingpong.c
- simple/cq_data.c
- simple/dgram.c
- simple/dgram_waitset.c
- simple/msg.c
- simple/msg_epoll.c
- simple/msg_sockets.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_rma_simple.c
- simple/rdm_rma_trigger.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_peek.c
- simple/scalable_ep.c
- streaming/msg_rma.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
- unit/size_left_test.c
This will make it easier to identify and remove duplicate code.
> Use common variable names for all fabtests

- pingpong/msg_pingpong.c
Commit e121c2616aabdf57a620b523e534c9120760fc2c replaced 2 memory
regions with one.  However, it did not adjust the size of the
memory region.  Ensure that the entire buffer has been registered.
> msg_pingpong: Fix memory registration call

- simple/msg_sockets.c
The error return EAI_SYSTEM for getaddrinfo() and getnameinfo()
indicates that the user should check errno for the cause of the error.
This test previously did the wrong thing everywhere that EAI_SYSTEM could
be returned, and this commit fixes the code to print the correct error
string using strerror(errno).
This commit fixes Coverity CID 131051.
Signed-off-by: Patrick MacArthur <pmacarth@iol.unh.edu>
> Correct error strings on EAI_SYSTEM

- common/shared.c
- include/shared.h
- pingpong/msg_pingpong.c
- pingpong/rdm_cntr_pingpong.c
- pingpong/rdm_inject_pingpong.c
- pingpong/rdm_pingpong.c
- pingpong/rdm_tagged_pingpong.c
- pingpong/ud_pingpong.c
- simple/cq_data.c
- simple/dgram.c
- simple/dgram_waitset.c
- simple/msg.c
- simple/msg_epoll.c
- simple/msg_sockets.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_rma_simple.c
- simple/rdm_rma_trigger.c
- simple/rdm_tagged_peek.c
- streaming/msg_rma.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
Create a shared version of bind_ep_res(), which is duplicated
by most apps to some degree.  There are a couple of instances
where a shared call cannot easily be used, such as the scalable
endpoint test.  Those are left unchanged.
About half the apps post an initial receive buffer in
bind_ep_res().  Use a parameter to indicate if a receive
should be posted.  Subsequent work will examine if all apps
can be made consistent in this area.
> Used shared call to bind resources to an EP

- Makefile.am
- pingpong/msg_pingpong.c
- pingpong/pingpong_shared.c
- pingpong/pingpong_shared.h
- pingpong/rdm_pingpong.c
- pingpong/ud_pingpong.c
- scripts/runfabtests.sh
This is an initial attempt at reducing some of the duplication inside of msg_pingpong, rdm_pingpong, and ud_pingpong. The extracted functionality was only really found in the pingpong tests so I made a new file 
inside of the pingpong subdirectory.
This came out of an attempt to add data verification to the three main pingpong tests.
@shefty I'm not sure what your plans were for refactoring this, but here's a start. rdm_pingpong, msg_pingpong, and ud_pingpong now support verification and prefix mode. I'd eventually like to add completion length checking as well (and associated flag), but that probably won't get added until a future PR. That's the reason recv_msg now takes a size.
Thoughts?
@goodell @jsquyres 
> Extract some pingpong functionality into common space

- common/shared.c
> common/shared.c: Negate ret before passing to fi_strerror.

- Makefile.am
List pingpong_shared.h in the relevant pingpong test _SOURCES variables
to ensure that it is installed.
@goodell @jsquyres @shantonu 
> Makefile.am: Add pingpong_shared.h to distribution tarball.

- common/shared.c
- include/shared.h
- pingpong/msg_pingpong.c
- pingpong/pingpong_shared.c
- pingpong/pingpong_shared.h
- pingpong/rdm_cntr_pingpong.c
- pingpong/rdm_inject_pingpong.c
- pingpong/rdm_pingpong.c
- pingpong/rdm_tagged_pingpong.c
- pingpong/ud_pingpong.c
- simple/cq_data.c
- simple/dgram.c
- simple/dgram_waitset.c
- simple/msg.c
- simple/msg_epoll.c
- simple/msg_sockets.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_rma_simple.c
- simple/rdm_rma_trigger.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_peek.c
- simple/scalable_ep.c
- streaming/msg_rma.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
This change gives us separate memory buffers for the send and receive side, which is necessary for data verification.  This is a re-post of just the first patch in my previous pull request.
> Use separate buffers for send and receives

- scripts/runfabtests.sh
Run fi_msg_pingpong, fi_ud_pingping, fi_rdm_pingpong in standard tests
without data verification or prefix enabled.
This helps catch issues introduced by verification or prefix.
@goodell @shefty @jsquyres 
> runfabtests.sh: Run pingpong tests without verification or prefix.

- common/shared.c
Work-around for psm provider not supporting binding EP to EQ.
Update of Ben's patch, which no longer applies after my previous merge.
> Fixes to fabtests to allow psm provider to pass tests

- simple/cq_data.c
The C standard indicates that bit shifts greater than the size
of the data type results in undefined behavior.  We see this
in the cq_data test, where shifting 1 << 64 results in an
answer of 1, rather than 0.  Trap for this.
Set the missing CQ wait object.
> cq_data: Set CQ wait object and avoid > 64-bit shifts

- simple/cq_data.c
- simple/rdm_shared_ctx.c
In case there is error during running <code>run_test</code>, return the error value.
> Added missing returns in the error path

- simple/cq_data.c
wait_for_completion uses fi_cq_entry, where as the completion entry is of type fi_cq_data_entry, resulting in stack corruption.
> Fix stack corruption in CQ data test

- common/shared.c
- streaming/msg_rma.c
- streaming/rdm_rma.c
Some providers would require local memory descriptor to be passed.
If there is a registered memory region, pass the local memory
descriptor to fi_sendmsg.
> ft_finalize: Pass local memory descriptor to fi_sendmsg

- common/shared.c
- include/shared.h
- pingpong/msg_pingpong.c
- pingpong/pingpong_shared.c
- pingpong/pingpong_shared.h
- pingpong/rdm_cntr_pingpong.c
- pingpong/rdm_inject_pingpong.c
- pingpong/rdm_pingpong.c
- pingpong/rdm_tagged_pingpong.c
- pingpong/ud_pingpong.c
- simple/cq_data.c
- simple/dgram.c
- simple/dgram_waitset.c
- simple/msg.c
- simple/msg_epoll.c
- simple/msg_sockets.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_rma_simple.c
- simple/rdm_rma_trigger.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_peek.c
- simple/scalable_ep.c
- streaming/msg_rma.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
- unit/size_left_test.c
Replace the dozen or so init_av() duplicate definitions of init_av()
with a common implementation.
In order to insert the remote address of the client side of the
test, a message exchange is needed to provide the server with the
client address.  This requires moving the initial control message
exchange into common code.
That address exchange trickles throughout the code in order to
ensure that receive buffers are posted before sends are initiated,
provide enough buffer space for addressing, and handle FI_PREFIX
correct (for those apps that already support it).
> Move init_av calls into common code

- common/shared.c
- pingpong/msg_pingpong.c
- pingpong/rdm_cntr_pingpong.c
- pingpong/rdm_inject_pingpong.c
- pingpong/rdm_pingpong.c
- pingpong/rdm_tagged_pingpong.c
- pingpong/ud_pingpong.c
- simple/cq_data.c
- simple/dgram.c
- simple/dgram_waitset.c
- simple/msg.c
- simple/msg_epoll.c
- simple/msg_sockets.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_rma_simple.c
- simple/rdm_rma_trigger.c
- simple/rdm_shared_ctx.c
- simple/rdm_tagged_peek.c
- simple/scalable_ep.c
- streaming/msg_rma.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
- unit/av_test.c
- unit/dom_test.c
- unit/size_left_test.c
Nearly all tests open the domain immediately after opening
the fabric resources (fabric and eq).  Move opening the
domain into the common code.
There are a couple of exceptions to this.  The server
side of connected endpoints defer opening the domain until
the connreq is received.  And a couple of unit tests open
the domain differently.
> Move fi_domain() into ft_open_fabric_res()

- complex/test_configs/sockets.json
- complex/test_configs/verbs.json
This commit adds config files that runs tests specific for one provider. Verbs and sockets provider tests are added now. PSM tests would be added later.
> complex: Add fi_ubertest config files for verbs and sockets providers

- common/shared.c
Removed -v option to display versions since none of the tests used it.
> common: Removed unused option to display version number

- common/shared.c
- complex/ft_comm.c
- simple/rdm_shared_ctx.c
- simple/scalable_ep.c
- streaming/rdm_multi_recv.c
Chnaged the return value of the calling function from <code>return ret</code> to <code>return -1</code>. Since we treat 0 as a successful return value and in case, we insert 1 address and av_insert returns 0, the calling function will return 0(success) which is wrong. Resolves #163 
@a-ilango, can you please review?
> av_insert: Fixed the return value of the calling function

- common/shared.c
- include/shared.h
- pingpong/msg_pingpong.c
- pingpong/pingpong_shared.c
- pingpong/pingpong_shared.h
- pingpong/rdm_cntr_pingpong.c
- pingpong/rdm_inject_pingpong.c
- pingpong/rdm_pingpong.c
- pingpong/rdm_tagged_pingpong.c
- pingpong/ud_pingpong.c
- simple/rdm_tagged_peek.c
- streaming/msg_rma.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
Provide a common implementation for sending, receiving,
and completion process.
This will help all test apps support (with additional changes)
the FI_PREFIX and FI_CONTEXT mode bits.
As part of this change, we assign a virtual tx sequence number
to each sent message.  The receiving side matches this with
an rx sequence number.  The sequence numbers are used as tags
when dealing with the tag matching interface.
Completion processing is updated to count the number of entries
that have been retrieved from a CQ.  Calls are updated to wait
until a total number of completions have occurred, rather than
waiting for X new completions.  This will allow CQs to be
converted to counters more easily.
This change fixes several places where fi_context structures
were reused before a previous request …
> Use common code for message processing

- scripts/runfabtests.sh
This commit gets the script working on OSX, with a goal of providing
an argument-less invocation that requires no set up.  This is intended
to be used as a quick check, as is used in the brew formula test I
have set up for fabtests.
- Allow the script to be run with no arguments.  This will keep us
from having to fiddle with the brew test if we decide to change the
way arguments are parsed, etc.  The default behavior is to use the
sockets provider with loopback.
- Add loopback-only testing mode that simply runs the commands without
ssh.  This allows someone to run the script without doing anything
(e.g., setting up keys).
- Add arguments to mktemp that mimics the default behavior for linux
- Do not use the -r argument to xargs for OSX (default behavior already)
- Remove nanoseconds from …
> Updates runfabtests.sh for OSX, homebrew, and other little things.

- scripts/runfabtests.sh
Remove the set -x command that prevents PATH variable from getting set for the test_exe command. Will add this again in another PR.
> runfabtests: Remove set -x for test commands.

- Makefile.am
> Enable -vvv option for runfabtests to debug fi_msg_epoll failure in CI

- Makefile.am
- configure.ac
- simple/msg_epoll.c
> Make fi_msg_epoll no-op on systems without it.

- simple/msg_epoll.c
The server pre-posts a receive buffer during initialization.
Posting again can result in the receive being posted after
the client has disconnected, resulting in a test failure.
> fi_msg_epoll: Remove unneeded fi_recv call from simple server tests

- complex/ft_config.c
strncpy uses sizeof info->node, rather than info->service,
which is the destination string.
Also fixes coverity issue on possible string buffer overrun
> ubertest: Fix reference to wrong string field

- scripts/runfabtests.sh
#387  broke timeout when ssh-ing to nodes. This patch fixes that.
> runfabtests: Fix timeout when ssh-ing to nodes

- streaming/rdm_rma.c
This patch fixes a regression introduced by 80565052.
> streaming: Pass remote_fi_addr for rma read/write fns.

- common/shared.c
- ported/libibverbs/rc_pingpong.c
- simple/msg_sockets.c
- simple/rdm_shared_ctx.c
- unit/av_test.c
- unit/dom_test.c
- unit/eq_test.c
- unit/size_left_test.c
- Used strtol which detect errors during conversion, instead of atoi
- Fixed some uninitialized variables
- Fixed potential memory when dynamic memory stored in 'hints->fabric_attr->prov_name/name' allocated via strdup can be lost if the option is supplied multiple times
- Added check in error path
- iters could overflow and make msg_index -ve. Used an unsigned type to fix it
- sockaddrstr could return NULL and FT_ERR would try to deference it. Added a NULL check to fix it
> Pr/cleanup: Handled boundary check, memory leak and other minor fixes

- complex/ft_msg.c
The inject testing cannot wait for a completion, so relies on
checking for EAGAIN.  The test loop currently calls 'transmit',
followed by checking for completions (to force progress, if
needed), and calls fi_tx_size_left.  The size_left call is
unneeded and can add additional latency.  Remove it and just
loop on the transmit calls.
> ubertest: Simplify EAGAIN inject testing loop

- ported/libibverbs/rc_pingpong.c
- scripts/runfabtests.sh
- Fix inconsistency in the results. This was due to recvs not being
posted before the connection is established.
- Fix -e option not to expect an argument.
- fi_cq_sread accepts count of work completions and not the size.
- Add fi_rc_pingong -e test to runfabtests
- If user passes an interface using -s option use it when running av
test.
> Fixes for fi_rc_pingpong and add a test to runfabtests

- pingpong/rdm_tagged_pingpong.c
This test only uses the tagged interfaces.  Remove the
request for FI_MSG interfaces.
> rdm_tagged_pingpong: Remove need for FI_MSG support

- autogen.sh
simple/info.c was moved into libfabric.  Use a different file.
> autogen: Fix reference to deleted file

- pingpong/msg_pingpong.c
- ported/libibverbs/rc_pingpong.c
- simple/cq_data.c
- simple/msg.c
- simple/msg_epoll.c
- simple/rdm_shared_ctx.c
- simple/scalable_ep.c
- streaming/msg_rma.c
Rationale: requiring usage of FI_SOCKADDR address format makes sense only if you are actually planning to manipulate a struct sockaddr in your application code. In many test this isn't the case, as addressing information is treated as opaque. For this use case it's better to use FI_FORMAT_UNSPEC (which is valued as 0, so it is the default if nothing is specified thanks to calloc). This pull request allows many tests to run on providers which are unable to handle IP addresses, such as https://github.com/alpha-unito/libfabric-provider-dpa.
Signed-off-by: Paolo Inaudi <p91paul@gmail.com>
> Remove unused FI_SOCKADDR addr_format specifications

- configure.ac
Update the version number to 1.3.0a1 and update the long-stale email
address to point to the OFI WG mailing list.
> configure.ac: update version and email address

- common/shared.c
- include/shared.h
- streaming/rdm_atomic.c
Extended the existing structure so that the test 
- Runs for all supported atomic ops
- Runs for all supported datatype
- Reports perf data for running individual atomic op for a particular datatype
- Removed local tostr() functions to use fi_tostr
@a-ilango, @shefty, can you please review? 
> Extended rdm_atomic test to include all supported atomic ops and datatypes

- streaming/rdm_atomic.c
Fixed the size argument in snprintf call to avoid buffer overrun.
> rdm_atomic: Coverity scan fixes

- scripts/runfabtests.sh
Since we extended rdm_atomic to run for all datatypes and all atomic ops in #405, now it takes longer time to finish. I decreased the iteration count so that it finishes in a reasonable time.
> runfabtests: Decreased the number of iters in rdm_atomic

- ported/libibverbs/rc_pingpong.c
- simple/poll.c
- simple/rdm_tagged_peek.c
- According to manpage, fi_cq_sread() cannot use FI_WAIT_NONE as wait_obj. Updated <code>rdm_tagged_peek.c</code> to specify completion method FT_COMP_SREAD which overrides the default wait_obj from FI_WAIT_NONE to FI_WAIT_UNSPEC. Updated <code>rc_pingpong.c</code> to use FI_WAIT_UNSPEC directly in cq_attr
- Fixed a typo in log message
Verified with fabtests. Fixes #411.@shefty can you please review?
> Updated tests using fi_cq_sread to use FI_WAIT_UNSPEC instead of FI_WAIT_NONE

- common/shared.c
- include/shared.h
- unit/size_left_test.c
The UDP provider does not require memory registration, so does not
implement that call.  Modify the apps to avoid attempting to
register memory when it is not needed.
> Only register local memory if needed

- complex/ft_domain.c
- streaming/msg_rma.c
- streaming/rdm_rma.c
RMA data sinks and sources should use FI_READ and FI_WRITE
MR access permissions respectively.
> Use correct MR access flags.

- Makefile.am
- complex/ft_main.c
- scripts/runfabtests.sh
Not ready to be merged yet. Wanted to get some early feedback :)
- Modified complex/ft_main.c and added provider and test name as new options for ubertest
- Added config path as a variable constructed from $datarootdir/${PACKAGE_NAME}
- Added a new option in runfabtests.sh to accept configuration for complex tests
- Added ubertest config files as a part of package distribution
- Added a function in runfabtests.sh to run complex tests
To run ubertest: <code>runfabtests.sh -v -p bin_path -t quick sockets node1 node2</code>
This will run fi_ubertests from <code>$datarootdir/${PACKAGE_NAME}/test_configs/sockets/quick.json</code> config file.
I'll update the config file structure and format after #419 is merged
@pmmccorm @a-ilango @shefty
Signed-off-by: Shantonu Hossain …
> Added option to run fi_ubertest from runfabtests.sh

- include/unit_common.h
- unit/av_test.c
- unit/eq_test.c
- unit/size_left_test.c
unit-tests: Mark tests that return with -FI_ENOSYS as 'skipped', rather than failed.
> unit-tests: Mark tests that return with -FI_ENOSYS as 'skipped', rather than failed.

- Makefile.am
Must specifically list out all matching files in the Makefile.am
(vs. using wildcards).
> Makefile.am: cannot use * in automake dist listings

- simple/scalable_ep.c
- streaming/rdm_multi_recv.c
Both scalable_ep and rdm_multi_recv was printing the following error msg from <code>ft_free_res()</code>
<code>common/shared.c fi_close (-16) fid 2</code>
- scalable_ep was missing fi_close function call for scalable ep object.
- Fixed rdm_multi_recv so that it closes mr before closing domain in <code>ft_free_res()</code> call.
@a-ilango @shefty
> Fixed error during fi_close for scalable_ep and rdm_multi_recv

- common/shared.c
- include/shared.h
A patch to align the data buffers. This was part of #431.
> add an option to align data buffers

- simple/rdm_shared_ctx.c
Modified <code>rdm_shared_ctx.c</code> to include a pre-posted buffer to be consistent with other fabtests. 
@jithinjosepkl @shefty @sayantansur 
> Added a recv to avoid occasional rdm_shared_ctx test fail

- common/shared.c
When using the aligned option, also touch the memory
location so that the pages get allocated.
The MPI/SHMEM benchmarks seem to touch the locations first.
> touch memory locations to allocate pages

- benchmarks/pingpong_shared.h
- benchmarks/rdm_cntr_pingpong.c
Missed a call to ft_parsepongopts() that led to a program not reading inject size argument.
Missed removing an extern variable that is no longer needed.
> minor cleanups to benchmarks

- complex/ft_main.c
If the -u option is specified, then the filename is provided via optarg
and should be copied with strdup.
> Fix seg fault in ubertest

- common/shared.c
100k iterations take a long time, and don't really work for
any bandwidth tests that might have to do a window of outstanding
sends. For example, a typical bandwidth test might have to do 64 window
which means 640K iterations!
Besides, the performance data reported doesn't vary between 100k and 10k
(attached).
The MPI benchmarks seem to use 10k iterations for small messages.
On a decent server with sockets provider.
100K iterations:
[ssur@f006 fabtests]$ time ./benchmarks/fi_rdm_tagged_pingpong -f sockets -S all
bytes   iters   total       time     Gb/sec    usec/xfer
2       100k    390k        2.97s      0.00      14.86
3       100k    585k        3.08s      0.00      15.41
4       100k    781k        3.07s      0.00      15.36
6       100k    1.1m        3.10s      0.00      15.52
8 …
> shared: reduce iteration count

- common/shared.c
For better or worse, most MPI benchmarks print data in
Mega Bytes (MB) per second.
Without this patch, the MPI-like bandwidth tests will need
another function.
Is it OK for us to just print MB/s?
> shared: print bandwidth in MB/s

- scripts/runfabtests.sh
- simple/rdm_shared_av.c
- Added check to pass shared_av name only for client since the test shares the av between two client threads. Now it works fine if the client and server are run in the same node which is the case in Travis. Fixes #423 
- Added a return variable to avoid overwriting -ENODATA return value for error case  .
@sayantansur @jithinjosepkl 
> Added rdm_shared_av in runfabtests.sh

- simple/rdm_shared_av.c
If a provider doesn't support named AVs, then it will return FI_ENOSYS.
This should be propogated to the child.
@sayantansur @shantonu @shefty 
> Check the return status of opening the AV in the child.

- fabtests.spec.in
Included the test_config files that were not packaged in rpm.
@a-ilango @pmmccorm 
> Added test_config files to the rpm package to fix rpm build

- common/shared.c
- include/shared.h
- simple/rdm_shared_av.c
abstract out parent child communication into the common area.
these functions can be used by other tests that want to do
multi-process per node communications.
I will eventually use these for multi-pair messaging rate benchmark.
> common: move parent/child communication to common

- scripts/runfabtests.sh
Suffixes like 's' do not work with sleep on FreeBSD.
Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>
> runfabtests: use sleep without suffix

- benchmarks/msg_pingpong.c
- common/shared.c
- include/shared.h
- simple/cq_data.c
- simple/msg.c
- simple/msg_epoll.c
- simple/msg_sockets.c
- streaming/msg_rma.c
We use fi_info fields like tx_attr.inject_size in benchmark
tests. On the server side, the fi_info got from fi_getinfo
may not have complete info if the user hasn't specified a
particular domain. So wait until we get an fi_info through a
connection request and use it for reading attributes. Using a
separate fi_info struct for passive EP should help with this.
Also fix a memory leak in getaddr.
> common: Use a separate fi_info struct for passive EPs

- .travis.yml
The required steps of Travis CI are <code>install</code> and <code>script</code> where install is meant for installing the dependencies and script is for building. Without the script step, Travis CI was executing an default script step <code>./configure && make && make test</code> which was running the tests again.
- Moved libfabric installation as <code>install</code> step
- Moved fabtests build as <code>script</code> step
Fixes #471 @a-ilango 
> Fixed the steps that are required by travis ci to avoid an extra build step

- common/shared.c
- include/shared.h
- simple/msg_epoll.c
- unit/eq_test.c
Require libfabric version 1.3 and use fi_trywait when checking
native wait objects.
This PR will likely fail all travis testing.
> fabtests: Update tests to use fi_trywait

- README
@shefty 
Is there a reason we have README and README.md for fabtests? Could I just remove this and we can just distribute the README.md in the distribution? 
> Update fabtests README.

- common/shared.c
- unit/eq_test.c
These fixes should eliminate an occasional failure on our FreeBSD 32-bit testing platform.
> fixups for get_elapsed implementation and usage

- complex/ft_comm.c
- complex/ft_config.c
- complex/ft_domain.c
- complex/ft_endpoint.c
- complex/ft_main.c
- complex/ft_msg.c
- complex/ft_test.c
- scripts/runfabtests.sh
- Fixed ubertest run command in <code>runfabtests.sh</code> to enable it in OSX
- Added failure check for ubertest in <code>runfabtests.sh</code>
- Minor cleanups in <code>runfabtests.sh</code>
- Fixed segfault in ubertest with sockets provider in travis ci environment
- Added cleanups reported by valgrind
- Removed redundant call of <code>ft_open_control</code>
- Removed extra <code>ft_post_recv_bufs</code> at the end of the test
- Added debug prints in ubertest
Fixes #459 
@jithinjosepkl @a-ilango @shefty
> Enabled ubertest for OSX, fixed segfault and added valgrind cleanups in ubertest

- common/shared.c
Fixed the following build warning from travis-ci
<code>
common/shared.c:1522:37: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
if (snprintf(tx_buf, message_len, message) >= message_len)
</code>
> Fixed build warnings in travis

- scripts/runfabtests.sh
Travis reports frequent, but inconsistent failures with ubertest.
Disable ubertest until it runs more reliably.
> runfabtests: Disable running of fi_ubertest

- complex/ft_test.c
Added a fix for #485. Will submit a separate patch that restructures  ft_xcontrol structure.
@bturrubiates
> Pr/ubertest fix: Close ft_xcontrol mr before closing ep

- common/shared.c
If the pollset bumps the refcnt on the CQ when being associated then an
error will be thrown. Close the pollset before closing the CQs so the
refcnt is 0 at time of closing the CQs.
While implementing the pollset support for the usnic provider I encountered
that the tests close the pollset after closing the CQs. I don't think it should be
valid to close CQs that have been associated with a pollset without them being
removed or the pollset being destroyed first.
@shantonu @shefty 
> Close the pollset before closing the associated CQs.

- complex/ft_main.c
Example test info:
[verbs, bandwidth, send, FI_EP_MSG, FI_AV_UNSPEC, eq_wait_none, cq_wait_none, [FI_LOCAL_MR], [FI_MSG, FI_RECV, FI_SEND]]
> ubertest: Print more config in test info

- benchmarks/ud_pingpong.c
"-t" is already used for completion queue type in the shared code.
> fi_ud_pingpong: rename "-t timetout" to "-T timeout"

- scripts/runfabtests.sh
We need a larger timeout value for "all" configuration with sockets provider. Added an option to choose timeout value. The default is unchanged.
<code>Usage: runfabtests.sh -T 180 -t all sockets</code>
@a-ilango @shefty 
> runfabtests: Added an option to choose timeout value

- common/shared.c
@shefty 
Without this tests that use the FD functionality seemed to immediately fail.
> Allow polling to timeout when waiting for a completion.

- common/shared.c
Without: 
```
{ xfer_size: 64, iterations: 10000, total: 1280000, time: 1.199834, MB/sec: 1.066814, usec/xfer: 59.991699Mxfers/sec: 0.016669 }
```
With: 
```
{ xfer_size: 64, iterations: 10000, total: 1280000, time: 1.199910, MB/sec: 1.066747, usec/xfer: 59.995499, Mxfers/sec: 0.016668 }
```
@sayantansur 
@shefty 
> Fix machine readable output.

- README.md
- Add new releases badge that shows the latest stable release. If the
badge is clicked it will redirect to the latest release download page.
- Fix build badge to reflect fabtests CI not libfabric CI.
- Add coverity badge.
@shefty 
> Add releases information to README.md and misc fixes.

- scripts/runfabtests.sh
Better enable testing on FreeBSD, where the package system installs bash to /usr/local/bin.
> runfabtests: support bash in alternative location

- benchmarks/benchmark_shared.c
- benchmarks/rdm_tagged_bw.c
- benchmarks/rdm_tagged_pingpong.c
- common/shared.c
- include/shared.h
- simple/dgram_waitset.c
- simple/msg_epoll.c
- simple/poll.c
Add support of FI_CONTEXT for rdm/tagged benchmarks
Add handling of -FI_EAGAIN from inject in bandwith benchmark
> FI_CONTEXT for rdm/tagged benchmarks

- benchmarks/benchmark_shared.c
- common/shared.c
- include/shared.h
- simple/dgram.c
- simple/dgram_waitset.c
- simple/msg.c
- simple/msg_epoll.c
- simple/msg_sockets.c
- simple/poll.c
- simple/rdm.c
- simple/rdm_shared_av.c
- streaming/msg_rma.c
- streaming/rdm_atomic.c
- streaming/rdm_multi_recv.c
- streaming/rdm_rma.c
For different ep types e.g. scalable_ep, alias_ep etc. we need to send/recv data using a specific ep instead of the common <code>struct fid_ep</code> defined in <code>include/shared.h</code>. Instead of duplicating send/recv call in tests, this patch adds ep as an argument.
- Passed <code>struct fid_ep</code> as an argument to rx/tx/inject call
- Removed unused arguments for <code>ft_finalize</code> in some tests
@a-ilango @shefty 
> Pass struct fid_ep as an argument to send/recv call

- simple/rdm_tagged_peek.c
Related changes for verbs provider is under refactoring, PR will be published bit later.
So, failing of this test with verbs provider from current libfabric/master on this test is expected.
@a-ilango @shefty 
Signed-off-by:Evgeny Leksikov <evgeny.leksikov@intel.com>
> Add support rdm_tagged_peek test for ep_rdm without msg capability (verbs) 

- common/shared.c
- include/shared.h
- simple/rdm_rma_trigger.c
Modified triggered RMA example to use alias_ep for triggered operation. This adds a test path for alias_ep.
@sayantansur @jithinjosepkl @shefty
> rdm_rma_trigger: Modified the test to use alias ep for triggered RMA

- benchmarks/benchmark_shared.c
- benchmarks/msg_bw.c
- benchmarks/msg_rma_bw.c
- benchmarks/rdm_tagged_bw.c
- common/shared.c
- include/shared.h
Bandwidth tests use windows which increases the # of transfers. Reduce
iterations so that tests don't timeout when running runfabtests.sh
> benchmarks: Reduce iterations for bandwidth tests.

- configure.ac
The fi_trywait call was not introduced until libfabric 1.3 and several
of the fabtests make use of this functionality. Instead of failing
during compilation, fail early and make the problem more obvious.
@shefty 
> Check libfabric version during configure.

- complex/fabtest.h
It wasn't being used, anyway.
This relates to ofiwg/libfabric#2046
> complex/fabtest.h: remove use of rdma/fi_prov.h

- Makefile.am
- simple/cm_data.c
Test all powers of two between 1 and the maximum supported provider
size. This test makes some assumptions:
- If the max supported cm data size is exceeded, then the client
provider will return -FI_EINVAL and not attempt to send any data.
- MR is currently not enabled on this test.
- fi_getopt is usable on a passive endpoint.
I was writing this to help debug ofiwg/libfabric#1914.
> Add a test to test sending data with fi_connect and fi_accept.

- simple/cm_data.c
This previously worked because opt_size and cm_data_size are both size_t, but technically, we should be using the size of cm_data_size, because that's the item we want filled.
@shefty @bturrubiates This seems like a no-brainer, but please provide another pair of eyes to check this...
> cm_data.c: use the right item size

- benchmarks/benchmark_shared.c
One of the loop variables, j was being reset at window size + 1
which was causing out of bound access at ctx_arr[j] and memory
corruption.
> benchmarks: Fix incorrect window size calculation

- ported/libibverbs/rc_pingpong.c
Our Jenkins testing was hanging on this test on some platforms. I tracked the issue down to what I think is incorrect usage of `fi_freeinfo`. My fix is based on the usage in `simple/cm_data.c`.
> rc_pingpong: Free info handle before reuse

- common/shared.c
- complex/ft_comm.c
- complex/ft_main.c
- complex/ft_test.c
- include/shared.h
- man/fabtests.7.md
- scripts/runfabtests.sh
- simple/cm_data.c
- According to manpage <code>fi_shutdown</code> generates an FI_SHUTDOWN event. Added <code>fi_eq_sread</code> to handle the event.
- Added a memset before eq_sread after fi_listen
- Used FT_EQ_ERR macro for fi_eq_readerr case
- Added cm_data into runfabtests.sh
- Moved sockets communication code from complex folder to <code>common/shared.c</code> and <code>include/shared.h</code>
- Renamed ft_fw_* functions as ft_sock_* functions for clarification
- Added sockets synchronization code to address Travis failures
- Added an entry for cm_data in the manpage
@jithinjosepkl @bturrubiates 
> cm_data: Handled fi_shutdown event and added code to synchronize via socket communication

- include/freebsd/osd.h
> freebsd/osd.h: Include header for protocol macros

- include/unit_common.h
- unit/size_left_test.c
- Check for correct return value from fi_rx_size_left (-FI_EOPBADSTATE)
- Fix small type-o in TEST_RET_VAL macro
> Fix rx_size_left_err

- common/shared.c
- configure.ac
- include/shared.h
- simple/shared_ctx.c
- unit/common.c
- unit/size_left_test.c
This adds functionality to check the functionality of the size_left tests for `FI_EP_RDM`, `FI_EP_DGRAM`, and `FI_EP_MSG`. 
@shantonu I have issues with this with the sockets provider. The issue is that the size attribute of the tx or rx context is 256, but after enabling the endpoint the size left functions return 368. Is this a bug, or should I not count on those being the same in the test? 
Unfortunately, the common code was not flexible enough for me to really use. I had to add a separate setup/teardown function for the resources. I tried to leverage as much of the existing infrastructure as possible. 
This fixes #546.
Please review @jsquyres @goodell @shantonu
> Enable testing multiple endpoint types with size left test

- Makefile.am
- include/shared.h
- include/unit_common.h
- man/fabtests.7.md
- scripts/runfabtests.sh
- unit/av_test.c
- unit/common.c
- unit/cq_test.c
- unit/dom_test.c
- unit/eq_test.c
- unit/size_left_test.c
Added this test based on the unit test for EQ. For now it tests only opening and closing of a CQ. Sockets provider currently fails the test.
@shantonu @bturrubiates please review.
Update: Sockets provider doesn't exactly fail the test. It returns -FI_ENOSYS and the test is marked as skipped.
> unit: Add a unit test for CQ.

- simple/rdm_shared_av.c
- Fix segfault on client side when client does not support shared AV
- Fix hang that manifests when providers don't support shared AV by opening a shared AV on both ends
@shantonu @sungeunchoi
> Misc fixes for fi_rdm_shared_av test

- .travis.yml
- Autogen.sh failure in OS X similar to libfabric was seen with https://travis-ci.org/ofiwg/fabtests/builds/162009293. Added @jsquyres's fix (https://github.com/ofiwg/libfabric/pull/2360) that updates GNU Autotools.
@a-ilango 
> travis: Ensure that we have good GNU Autotools

- unit/cq_test.c
The CQ test attempts to open cq_cnt CQs, and errors if that fails.
This is resulting in travis errors as a result of open fd limits.
Because the cq_cnt is intended to reflect hardware limits, and not
system software limits, instead of having the test error, simply
report a warning and continue with additional tests.
> fi_cq_test: Convert error into warning

- scripts/runfabtests.sh
Yes, foo is so common that there are actually servers named
'foo', which causes it NOT to be a negative test case.  Use
a random string of garbage which is less likely to be a real
name.
> runfabtests: Rename foo host

- common/shared.c
- scripts/runfabtests.sh
- runfabtests: Set FI_ENODATA correctly for FreeBSD
- common: Set socket family in ft_socket_listen
> Updates for FreeBSD

- include/shared.h
- unit/size_left_test.c
> unit/size_left_test: For MSG endpoints an EQ should be bound before enabling it.

- benchmarks/benchmark_shared.c
- benchmarks/benchmark_shared.h
- common/shared.c
- complex/ft_main.c
- include/shared.h
- man/fabtests.7.md
- scripts/runfabtests.sh
- unit/av_test.c
- unit/common.c
- unit/cq_test.c
- unit/dom_test.c
- unit/eq_test.c
- unit/size_left_test.c
- Make provider name, domain name, fabric name, src port and dest port consistent in all the tests according to the discussion in #561
- Change ```runfabtests.sh``` is updated to use the modified options 
- Update manpage
- Use ft_parseinfo in unit tests to resolve options
```
New Usage:
-f fabric name
-d domain name
-p provider name
-B src port
-P dest port
```
@a-ilango
> options: Make provider/domain/fabric name and src/dest port consistent

- unit/getinfo_test.c
Since the NULL hints test doesn't use any hints attribute, a test
failure may not be attributable to the provider/fabric/domain that
we are testing. Remove this test. We have coverage for this code
path through fi_info test in libfabric.
> unit: Remove NULL hints test from getinfo unit test.

- common/shared.c
- include/shared.h
- unit/av_test.c
- unit/common.c
- unit/cq_test.c
- unit/dom_test.c
- unit/eq_test.c
- unit/getinfo_test.c
- unit/size_left_test.c
- Add a common function to print addr opts usage.
- Add fabric option to INFO_OPTS macro.
All files that use this macro call ft_parseinfo. So we should
be good.
- Define new FAB_OPTS macro.
- Allow some unit tests to make use of domain name option.
- Fix opts in fi_getinfo test.
This should fix #572
> Fix opts and usage

- Makefile.am
- common/osx/osd.c
- configure.ac
- include/osx/osd.h
The workaround for clock_gettime is only necessary when the function is
not already available. macOS sierra includes an implementation of
clock_gettime in libc.
- Only define implementations if HAVE_CLOCK_GETTIME is 0.
- Add AM_CONDITIONAL to define whether HAVE_CLOCK_GETTIME is defined.
This will be used to determine whether to compile the osx/osd.c file.
> Fix macOS Sierra build.

- unit/av_test.c
f3ff91ae changed -d --> -g and -D --> -G, respectively.  Update the
help message to match, and fix one trivial typo.
> av_test: fix help message

- include/osx/osd.h
Need <config.h> to get the definition of HAVE_CLOCK_GETTIME.
> osd.h: add <config.h>

- README.md
YMMV if you use libfabric vX with fabtests vY.
> README.md: indicate that version-matched pairs are best

- simple/shared_ctx.c
ft_alloc_active_res() opens an unnecessary endpoint with the same
port number as the first endpoint in the array of endpoints
which are subsequently bound to a shared TX context.  The sockets
provider somehow doesn't care if two endpoints with the same
address are opened (maybe the collision is only detected at
fi_enable), but for the GNI provider it is not allowed to
open two endpoints with the same ip addr/port.
To avoid this call ft_alloc_ep_res() instead.
Signed-off-by: Howard Pritchard <howardp@lanl.gov>
> shared ctx test: do not open unnecessary ep

- benchmarks/rdm_cntr_pingpong.c
Currently the rdm_cntr_pingpong test does not
specify a FT_WAIT_TYPE when setting up. According
to the man page, fi_cntr_wait can only be used when
configured with a wait_object. This change adds
FT_COMP_SREAD, which maps to FI_WAIT_UNSPEC under
the covers so that the test can use fi_cntr_wait without
getting stuck in an infinite loop.
Signed-off-by: James Shimek <jshimek@cray.com>
> Specify cntr wait type in pingpong test

- common/shared.c
- simple/msg_sockets.c
- unit/av_test.c
Add back socket headers removed in 87e9d2ff. Builds on Linux must be
including these indirectly, but FreeBSd currently fails.
Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>
> shared.h: Add back socket headers for common code

- simple/dgram_waitset.c
Before this change, the receive for the message was posted by the client
as the final step of the initialization process. The server can
sometimes finish initialization and post the send containing the
message before the client has completed posting a receive buffer. Post
an extra receive buffer to handle the message and synchronize to allow
the client to complete posting the buffer.
Signed-off-by: Ben Turrubiates \<bturrubi@cisco.com\>
> dgram_waitset.c: Fix a race condition.

- streaming/rdm_rma.c
- unit/mr_test.c
Plus a bonus fix to a compiler warning
> fi_rdm_rma: Leave FI_CONTEXT mode bit unset

- configure.ac
To match the libfabric v1.4.1 release.
> configure.ac: bump to v1.4.1

- include/shared.h
- parameter retv in macro was not wrapped by () which may cause
unpredicted behavior in some cases
Signed-off-by: Oblomov, Sergey <sergey.oblomov@intel.com>
> fixed potential issue in FT_PRINTERR macro

- simple/msg_sockets.c
- in the function setup_handle there is free of src_addr
value of fi_pep object. For Linux OS it works fine because
provider uses mem_dup call to copy src_addr buffer. But
on other OS-es (we are working over port of fabtests
to Windows) such freeing cause crash
fix: do not free values manually, just save it into temporary
variable and restore later (to avoid resource leaks)
Signed-off-by: Oblomov, Sergey <sergey.oblomov@intel.com>
> msg_sockets: fixed issue in src_addr manipulation

- Makefile.am
- common/shared.c
- complex/ft_main.c
- include/shared.h
- scripts/runfabtests.sh
- simple/msg_sockets.c
- unit/cntr_test.c
- unit/getinfo_test.c
- unit/mr_test.c
Cleaned up end of line white space.  Copied getenv() results, since a putenv() call can modify the returned buffer.
> unit/getinfo: Manual merge of updates to getinfo test

- unit/eq_test.c
EQs may grow dynamically and are not restricted to the specified
size.  Remove unnecessary check from eq_test.
Fixes #585
> unit/eq_test: Remove overflow test

- common/shared.c
- unit/cntr_test.c
The following issues are fixed:
- Unintentional integer overflow
- Unchecked return value
- Bad bit shift operation
> Fix coverity issues in fabtests

- common/shared.c
- complex/ft_domain.c
- simple/cm_data.c
- unit/av_test.c
Fixed problem with CQ/EQ error reading, if passes fi_[cq|eq]_err_entry that is statically
allocated variable and not memset'ed by zero.
After implementation of CQ/EQ application's error buffer (if err_data_size of
fi_[cq|eq]_err_entry is not a zero, provider will use APP's buffer as much as
it's possible). In case of statically allocated structure, garbage contains
in its fields (err_data_size isn't a zero, but some positive value), provider
will fill error informatiuon to buffer that is not actually provided by
application (i.e. write/read unitialized and invalid buffer). This behavior
leads to crash of process.
Solution is just to memset fi_[cq|eq]_err_entry variables by zero to avoid
mentioned above behavior. Since test are not expected to provide some its own
buffer for error …
> Fixed problem with CQ/EQ error reading in fabtests

- simple/rdm_tagged_peek.c
I extended the tagged_peek test to include FI_CLAIM and FI_DISCARD flags testing as well.
Does this test look OK? Feedback?
This test has to do unexpected messaging, so it has some weird interactions with the common code, therefore there is a separate sync outside of the common code before the call to ft_finalize().
Also, the receive function has to use a different struct fi_context than rx_ctx since rx_ctx is global and is posted as a receive buffer for the next ft_sync().
> add FI_CLAIM and FI_DISCARD simple tests

- simple/shared_ctx.c
> Fix coverity issue in fabtests

- simple/rdm_tagged_peek.c
The test was using a hint of buffering up to 1K. The test now accepts arbitrary sized messages, so instead use FI_RM_ENABLED instead of providing the hint.
> use FI_RM_ENABLED in peek test

- common/shared.c
- include/shared.h
- unit/getinfo_test.c
- 	unit: Add short names to getinfo tests
- 	unit: Add a getinfo unit test for testing utility providers
- Also fix setting FI_PROVIDER env variable. If the user passed an utility
provider for prov_name we shouldn't filter out core providers unless a
core provider is also specified
The getinfo unit test for utility providers would fail until https://github.com/ofiwg/libfabric/issues/2892 is fixed.
> Updates to getinfo unit test

- common/shared.c
- complex/fabtest.h
- complex/ft_config.c
- complex/ft_domain.c
- complex/ft_main.c
- complex/ft_msg.c
- complex/ft_test.c
- include/shared.h
- streaming/rdm_atomic.c
- test_configs/sockets/quick.test
Enable atomic testing in ubertest, including all functions, operations, and datatypes.
> complex/fi_ubertest: add atomic testing

- complex/ft_test.c
> complex: Fix coverity issue - Unused value of ret after ft_send_rma()

- .travis.yml
- Makefile.am
- Fix incorrect path to ft_osd.h
- Create common variables for unit and benchmarks sources.
- Move header files from EXTRA_DIST to sources.
- Add 'make dist' command as part of Travis CI.
Fixes #643
> Fix incorrect path to ft_osd.h in Makefile and update Travis CI config.

- complex/fabtest.h
- complex/ft_config.c
- complex/ft_msg.c
- complex/ft_test.c
- test_configs/sockets/quick.test
Enhancements to mode bit testing, specifically addition of FI_CONTEXT support
> complex/fi_ubertest: add FI_CONTEXT

- streaming/rdm_atomic.c
fi_tostr returns a static string that gets overwritten by
multiple calls to it.
> rdm_atomic: Fix print statement

- scripts/runfabtests.sh
yeah, the test doesn't pass reliable -- disable until it can be fixed.
> dgram_pingpong: Fix data verification check

- streaming/rdm_atomic.c
Test will return if last datatype tested returns in success, skipping the rest of the tests. Change so that test only returns on actual error.
> streaming/rdm_atomic: change return check to run all ops

- scripts/runfabtests.sh
runfabtests script doesn't work with complex provider's names like verbs\;ofi-rxm.
Added quotes beyond ${PROV} variable to be able execute runfabtests with complex
provider's name
> common/scripts: Add support of complex name of provider in runfabtests script

- benchmarks/rma_bw.c
- common/shared.c
- 	Add missing FI_CONTEXT support in rma tests
-	common: Skip progressing if the provider supports auto progress
-	common: Add a function to progress the CQ for inject operations
> Add support to correctly progress CQ for inject operations

- common/shared.c
Return after fi_cntr_wait. No need to check for any errors. The caller
would handle those.
> common: Fix null pointer dereference of txcq (found by coverity).

- scripts/runfabtests.sh
ISPs have a wonderful feature where they redirect DNS queries
to completely bogus addresses to a valid address that doesn't
do anything.  This causes the negative address tests to fail.
Add an option to skip the negative tests.
> runfabtests: Add option to disable negative testing

- benchmarks/benchmark_shared.c
- common/shared.c
Don't post recv on the recipient side of rma write with immediate data, if provider doesn't require FI_RX_CQ_DATA mode.
> common: Update rma tests to check for FI_RX_CQ_DATA before posting a recv

- Makefile.win
- fabtests.vcxproj
- added /MTd /MT (Debug & Release) to match libfabric's C runtime library
- removed nonexistent netdir tests
- set compiler to v140
> win/build: fix project

- Makefile.am
- complex/ft_config.c
- complex/ft_endpoint.c
- complex/ft_main.c
- complex/ft_test.c
- test_configs/psm/all.test
- test_configs/psm2/all.test
Includes two patches to enable full psm support.
Connection switch:
- previously, client parsed config file and connected before server, causing an address resolution issue with psm providers
- patch switches connection so client connects only after server has connected
Process creation:
- psm2 does not strictly support opening multiple contexts within the same process, causing problems when running multiple tests
- to resolve this issue, this patch adds a fork during each iteration to ensure that every test is its own process, allowing the test to run any number of tests reliably
Adds psm and psm2 config files for testing.
These patches have been verified with sockets, psm, psm2, and verbs.
> complex/fi_ubertest: psm/psm2 suppport

- simple/msg_sockets.c
- If source address provided as domain name, the first address in ai list may be IPv6.
- In this case subsequent fi_getinfo will return -120.
PR:https://github.com/ofiwg/libfabric/pull/3024 adds debug log message when such error occurs.
> simple/msg_sockets: use only IPv4 addresses

- .appveyor.yml
Added `.appveyor.yml` to support Windows testing of libfabric in fabtests repository
1. Sign in on https://ci.appveyor.com
2. click **NEW PROJECT** -> hover on **fabtests** -> click **ADD**
3. fabtests -> click **SETTINGS** -> **General**:
a) set **'Build version format'** to: `{build}`
b) set **'Custom configuration .yml file name'** to: `.appveyor.yml`
c) check **'Skip branches without appveyor.yml'**: `on`
4. Merge the PR. New build will start automatically.
> win/ci: added config file

- include/windows/osd.h
- unit/eq_test.c
Some tests with time checking fail from time to time
Improve clock_gettime realization for Windows to make it more accuracy
> osd/windows: Improve clock_gettime for Windows

- simple/rdm_deferred_wq.c
> simple/rdm_deferred_wq: fix an incorrect parameter causing Travis failure

- common/shared.c
The call to fi_query_atomic should specify the correct set
of flags (FI_FETCH_ATOMIC, FI_COMPARE_ATOMIC) in order to
validate if atomic fetch and atomic compare operatons are
supported.  Otherwise, the check defaults to base atomic
operations.
> shared: Fix check_atomic_attr call

- Makefile.am
https://github.com/ofiwg/libfabric/pull/3122 changed the utility provider name prefix from "ofi-" to "ofi_". Update the test to reflect the same.
> Use the new prefix for utility provider names

- common/shared.c
- used inttypes defines to set tag format
Signed-off-by: Oblomov, Sergey <sergey.oblomov@intel.com>
> common: suppressed type-mismatch warning

- unit/getinfo_test.c
unit/getinfo_test
- Added test to validate that a provider sets the supported msg_ordering bits
- Added tests to validate that a provider allows valid RMA ordering sizes
- Added tests to validate that a provider checks invalid RMA ordering sizes
Signed-off-by: Neil R Spruit <neil.r.spruit@intel.com>
> unit/fi_getinfo_test: Added MSG/RMA Ordering testing

- complex/ft_comp.c
- complex/ft_main.c
- complex/ft_test.c
> ubertest: Fix coverity issues for mixed enum values

- Makefile.am
- test_configs/sockets/complete.test
- simplify quick.test by removing tests (mostly atomic datatype/op combinations) to actually make the test "quick"
- move all combinations in old "quick.test" to new "complete.test" file that tracks all ubertest abilities and combinations
Fixes ofiwg/libfabric#3145
> test_configs/sockets: quick.test simplification

- complex/fabtest.h
- complex/ft_comp.c
- complex/ft_config.c
- complex/ft_main.c
- complex/ft_test.c
- test_configs/sockets/complete.test
- clarify use of wait object for both CQs and counters
> complex/fi_ubertest: add cntr_wait_obj

- Makefile.am
- common/shared.c
- include/shared.h
- scripts/runfabtests.sh
- simple/multi_ep.c
- simple/multi_mr.c
- simple/rdm_multi_domain.c
- simple/recv_cancel.c
- simple/unexpected_msg.c
Implemented new Functional tests for verifying:
- Multiple Memory Regions in use for sending messages between client/server to specified memory regions
- Multiple Domains in use for sending messages between client/server to specified domains
- Multiple Endpoints communicating between client/server created on a single domain.
- Cancelling a pending Receive and retrieving the correct error log.
- Unexpected messages handled by the provider
Implemented support in the common infrastructure for:
- allowing easier setup of new RDM/DGRAM endpoints
- increase ease of init for connect/accept FI_EP_MSG endpoints for multi ep init
- added new init for CM (connect/accept) FI_EP_MSG testing
- configurable address vector size
- configurable tag for tagged messaging
- configurable option to enable …
> Multi Memory Region, Multi Domain, Multi Endpoint, Recv Cancel, & Unexpected_msg FT

- scripts/runfabtests.sh
fi_multi_ep is a new test, however it fails frequently for the udp
provider.  Remove dgram testing as part of the runfabtests script.
> multi_ep: Remove testing of udp provider

- scripts/runfabtests.sh
This test still fails frequently.  It's not clear if this is an
issue with the test or socket provider.  Disable for now to not
block other PRs, while the cause is determined.
> multi_ep: Disable automatic testing until failure is resolved

- benchmarks/rma_bw.c
- simple/multi_mr.c
- simple/rdm_multi_domain.c
- simple/unexpected_msg.c
- streaming/msg_rma.c
- streaming/rdm_rma.c
RMA tests that use the writedata operation should indicate that
remote CQ data is required.  Do this by specifying a non-zero
remote_cq_data domain attribute.
> rma tests: Request support for remote CQ data for writedata

- complex/fabtest.h
- complex/ft_domain.c
- complex/ft_msg.c
- complex/ft_verify.c
More thoroughly test inject functions by changing buffer content right after send.
Requires a new copied transfer buffer for validation purposes.
> complex/fi_ubertest: change inject buffer right after send

- scripts/runfabtests.sh
Both tests continue to show hangs in travis.  They may be pointing
to issues with the socket provider, but until the failures are
resolved, disable from travis testing.
> multi_domain/ep: Disable from travis testing

- streaming/rdm_atomic.c
- GCC compiler complains that `ret` variable may be unitialized in scope
of `run_op()` function. Since there is `default:` baranch in the
`switch-case` construction, it is impossible case. Anyway make GCC happy
in this case.
the peace of Travis CI testing output:
```
streaming/rdm_atomic.c:328:2: error: ‘ret’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
return ret;
```
- Replace the statement expression by the `static inline` function to be compliant old compilers that don't support this expression:
https://stackoverflow.com/questions/6440021/compiler-support-of-gnu-statement-expression - The version of the compilers that supports this feature (but it may be mistaken). the Intel Compiler 15.0 (for Windows) doesn't support this feature, but the MSVC compiler …
> streamin/rdm_atomic: Fix GCC ungrounded warning

- complex/fabtest.h
- complex/ft_comp.c
- complex/ft_config.c
- complex/ft_main.c
- complex/ft_test.c
Updates/Fixes to Ubertest including:
- Fix to ubertest to set cq_data_size when testing FI_REMOTE_CQ_DATA
- Added support for handling multiple fi_info structs for providers allowing for multi network device/config in testing
- Fixed ubertest to always open and bind a CQ to active endpoints for TX/RX event handling
- Fixed ubertest to support testing RMA/Atomic Counter completions by setting FI_RMA_EVENT given RMA/Atomic Counter completions are expected
- Added support to ubertest to allow test cases that get both CQ & CNTR completions in the same test case
> Ubertest Updates/Fixes

- benchmarks/rma_bw.c
- common/shared.c
- include/shared.h
- streaming/msg_rma.c
- streaming/rdm_rma.c
The RMA capability bit is independent of memory registration.
Restructure the processing of rma_op command line options, so that
the op can be used to configure the hints passed into fi_getinfo.
This fixes an issue where the local access (e.g. FI_WRITE or FI_READ)
end up being lost when an rma_op is specified.  Additionally, it
avoids modifying the returned fi_info, and instead updates hints
prior to them being used.
> shared: Fix mapping RMA tests to RMA capabilities

- Makefile.am
- common/shared.c
- include/shared.h
- streaming/resmgmt_test.c
-streaming/resmgmt_test functional test (fi_resmgmt_test)
- Allows for setting the TX/RX CQ sizes and overflowing the queues
- Allows for altering the TX/RX Context size
- Configurable size for the messages sent
- Configurable number of operations
- Can set to share CQs between TX/RX
- Configurable transfer sizes
- Tests Tagged/Untagged messaging
- Configurable to force AV table for EP_RDM/EP_DGRAM
- Verbose printing configurable
- Supports dgram,msg,rdm endpoint types
-common/shared
- Added option to allow shared CQs between TX/RX ops
- Added options allowing for setting the TX/RX CQ sizes
Change-Id: I302410559cb0276e067ed2fef71345ea335d77d0
> streaming/fi_resmgmt_test: Resource Management Functional Test

- benchmarks/benchmark_shared.c
- common/shared.c
- include/shared.h
- simple/dgram_waitset.c
- simple/msg_epoll.c
- simple/multi_ep.c
- simple/poll.c
- simple/recv_cancel.c
- simple/unexpected_msg.c
-simple/unexpected_msg
-Added support for sending Remote CQ data for testing
-common/shared
-Added support in ft_post_tx to send CQ data for tagged and
untagged messages
-Added define for NO_CQ_DATA to be passed to ft_post_tx
-Updated all uses of ft_post_tx to use NO_CQ_DATA unless testing
CQ data passing
Change-Id: I0da3bcd6a30b7afa34d1968d938b03ff3df21616
> simple/unexpected_msg: Added Support for Remote CQ data testing

- scripts/runfabtests.cmd
Disable the test until the root cause is identified and fixed
> runfabtests.cmd: Disable domain test for windows

- Makefile.am
- scripts/runfabtests.sh
- test_configs/osx.exclude
- test_configs/udp/udp.exclude
- test_configs/verbs/verbs.exclude
- Increase runfabtests.sh output width for better alignment
- User can now specify a file containing a list of tests to exclude
- Add a strict mode which would treat -FI_ENODATA and -FI_ENOSYS errors
as failures
- Allow user to specify regular expression patterns in exclude tests
command line arg and in exclude file.
- Added exclusions list for verbs and udp providers
- Add OS specific exclusions in Makefile
This is a follow-up for PR #670
> runfabtests.sh: Add option to specify test exclusions file

- Makefile.am
- common/shared.c
- include/shared.h
- scripts/runfabtests.sh
- simple/inj_complete.c
-simple/inj_complete functional test (fi_inj_complete)
- Tests setting FI_INJECT_COMPLETE completions for TX ops
- Allows for testing with fi_send/fi_recv or fi_sendmsg/fi_recvmsg
- data verification on messages is available
- Checks that tx buffer modifcations can be done after injection
event
- Added injection overrun testing to ensure only the
first buffer is accepted
- Supports dgram,msg,rdm endpoint types
- Added to simple test list
-common/shared
- Added ft_recvmsg for posting a recv for an ep with different
flags
- Added ft_sendmsg for posting a send for an ep with different
flags
- ft_cq_read_verify for reading a CQ entry and check that the
context returned is correct
Change-Id: Ibe411796d29bb24217b5303c17fb416e4dbb51b2
> simple/fi_inj_complete: FI_INJECT_COMPLETION FT

- Makefile.win
- common/shared.c
- fabtests.vcxproj
- fabtests.vcxproj.filters
- simple/inj_complete.c
- test_configs/udp/udp.exclude
This patch was prepared to reach he following goals:
- Add missed compability to be able use this test for the verbs, psm, sockets, RxM providers at least
- In addition to the checking of the `op_context`, add the verification of the tag
- Fix a small bag - App should pass an array of the MR's desc rather a pointer to the MR desc for the fi_[send|recv]msg functions
- Exclude `fi_inj_complete` test for the prov/udp, because UDP doesn't support FI_TAGGED
- Add `fi_inj_complete` test to the VS project and Makefile.win 
> simple/inj_complete: Add possbility to use verbs/psm providers

- simple/rdm_tagged_peek.c
A second level of indirection was needed for the desc field in the struct fi_msg_tagged_msg.
> simple/rdm_tagged_peek.c: Fix indirection level bug with desc in tag_queue_op().

- Makefile.am
- scripts/runfabtests.sh
- test_configs/psm2/verify.test
- test_configs/sockets/verify.test
- add scripts to run ubertest with verification for sockets and psm2
- add option to runfabtests.sh to run ubertest verification with added scripts
- modify runfabtests.sh complex test command (sometimes causing failure with source option)
*Verified passing with sockets. Psm2 in testing due to a recent ubertest bug causing problems with actually running it. All of the tests in the config file should be passing psm2 after those issues are resolved.
> complex/fi_ubertest: add verification scripts

- common/shared.c
-Currently the use of ft_tag_is_valid does not take into account the ft_tag
variable for custom tags in fabtests. This results in the calls to ft_tag_is_valid
failing if ft_tag is used.
-To resolve this issue the calls in the common framework to read
completions has been fixed to check if ft_tag is set
Change-Id: I18501a3a296df4ac965f6234a3598dd7b741b36b
> common/shared: Fixed ft_tag_is_valid to check ft_tag if set

- Makefile.am
- simple/resource_freeing.c
-Simple test which will open/close OFI resources and will detect if
opening or closing a resource fails.
-Can be used to check for memory leaks during resource allocation/free in a
provider.
Change-Id: I2f3cf2550c1070ed4e06a6ec94480413e2435a2d
> simple/resource_freeing: OFI Resource alloc/free test

- .appveyor.yml
- Makefile.win
- fabtests.sln
- fabtests.vcxproj
- fabtests.vcxproj.filters
The intent of this PR is to add the support of the new version of the VS toolset (v141) that is used for the Visual Studio 2017. The following is done:
- Remove `readme.txt` file form the `fabtests.vcxproj`, because this file was removed
- Update Configuration's names in the `Makefile.win`
- Create four new configuration for the fabtests VS project:
* `Debug-v140` (the same as previous `Debug` conf)
* `Debug-v141` (the same as previous `Debug` conf, but this supports the v141 toolset)
* `Release-v140` (the same as previous `Release` conf)
* `Release-v141` (the same as previous `Release` conf, but this supports the v141 toolset)
- Updated AppVeyor script to support new configuration types for the fabtests.sln and libfabric.sln
**Note: This PR Should be merged with an appropriate …
>  common/windows: Add support of the VS 2017 (v141 toolset)

- .appveyor.yml
- Makefile.win
This fixes failing VS15/v141 jobs in the AppVeyor.
The v141 toolset is introduced together with VS17
This is impossible to compile VS15 configuration with v141 toolset
But the compiling VS17/v140 is kept for the AppVeyor to check backward compatibility of our VS project
**Note: Please merge this PR together with ofiwg/libfabric#3405 that fixes the same problem.**
Also this PR fixes format issues in the `Makefile.win`
> common/appveyor: Exclude testing VS15 with v141 toolset from AppVeyor matrix

- common/shared.c
-Currently, when calling ft_post_tx/rx it is expected that the common
framework has a valid mr allocated.
-This limits the tests developed for fabtests from using the common post
functions given the test does not allocate the mr
-To resolve this a check has been made to pass in NULL for the desc if
the mr is not set
Change-Id: I00c05797bd2280ca13bc8ae6d9e8444e9e160e73
Changes from Neil's patch - white space re-formatting, convert 0 -> NULL.
> common/shared: Updated ft_post_tx/rx to allow for NULL mr

- simple/recv_cancel.c
- simple/unexpected_msg.c
- test_configs/ofi_rxm/ofi_rxm.exclude
- test_configs/verbs/verbs.exclude
- Add exclude file for rxm provider and update verbs.exclude
- simple: Advertise support for OFI_MR_BASIC_MAP for recv_cancel, unexpected_msg tests
These tests don't use RMA so we can support OFI_MR_BASIC_MAP bits so that
some providers are not excluded for this test
> Update test exclusions and mr_mode bits for some tests

- common/shared.c
Commit cb0f9596 added always binding an EP to rx/tx CQs.  This
resulted in the EP generating all completions to the CQs, even if
counters are being used as the primary completion mechanism.
The result is that the CQs can fill up and never drain.
Fix this by using selective completions when binding to the CQs
when counters are in use.
> shared: Disable writing completions to a CQ if using counters

- complex/fabtest.h
- complex/ft_main.c
- complex/ft_test.c
-Updated the ubertest init to hold the client from calling getinfo until
after the server has opened all its resources
-Created a new ft_open_res that allows for opening the resources for a
process without requiring a sync with the client/server
-Exposed ft_cleanup such that resources can be freed on the server
given the client has run out of fi_infos to test and needs a new server
fi_info if it exists
Change-Id: I02f51d67e2f774c2a039d3f257f8d9048b205c63
> complex/ubertest: Fix ubertest to hold client getinfo until server init

- unit/getinfo_test.c
This adds a check for handling FI_MR_BASIC and FI_MR_SCALABLE mr_mode.
> getinfo_test: Several cleanups and tests for 1.0 mr_mode bits

- complex/ft_main.c
-Fixed calls to ft_open_res to use a stored fi_info on the server to
address an issue where ft_accept will overwrite the fabric_info with an
info that cannot be used to allocate the fabric and domain resources.
-This only affects the server side as ft_connect does not overwrite the
fabric_info on the client.
Change-Id: Id9d590d138b736ffdb101f7e99a34d05d5879a3e
> complex/ubertest: Fix open_res on server to use a stored fi_info

- unit/av_test.c
- unit/cntr_test.c
- unit/eq_test.c
- unit/mr_test.c
Several tests set mr_mode = ~0.  This results in setting
both FI_MR_BASIC and FI_MR_SCALABLE, in conjunction with
1.5+ mr_mode bits.  New checks in libfabric prohibit this
combination.
Remove setting the FI_MR_BASIC and FI_MR_SCALABLE bits.
> fabtests: Do not set all mr_mode bits

- streaming/rdm_rma.c
It enables support of this test for the verbs/RDM provider
> streaming/rdm_rma: Add FI_CONTEXT mode to be able run over verbs/RDM

- simple/rdm_tagged_peek.c
The API requires that the context passed to fi_recvmsg() for
FI_PEEK|FI_CLAIM be a struct fi_context and that the same fi_context
must be passed to FI_CLAIM. The prior code met the API in the sense
that the fi_context to FI_CLAIM would have the same address, but it
had gone out of scope since the FI_PEEK and the contents were
lost. Since some providers hide the pointer to the claimed entry in
the context, this can lead to segfaults.
Making the context global keeps the fix as small as possible and
is consistent with the way the tests are written.
> simple/rdm_tagged_peek.c: Keep context in scope between FI_PEEK|FI_CLAIM and FI_CLAIM.

- benchmarks/dgram_pingpong.c
- scripts/runfabtests.sh
- simple/cq_data.c
- test_configs/psm2/psm2.exclude
- test_configs/verbs/verbs.exclude
- simple: Expand CQ data test to support other EP types
- benchmarks: Add support for FI_CONTEXT in dgram_pingpong
- Add runfabtests exlusion list for psm2
- Add rdm_rma -o writedata test to verbs test exclusions
> Update cq_data, dgram_pingpong tests, add test exclusions for psm2

- benchmarks/dgram_pingpong.c
- common/shared.c
- include/shared.h
- simple/dgram_waitset.c
- simple/rdm_deferred_wq.c
- simple/rdm_rma_simple.c
- simple/rdm_rma_trigger.c
- simple/rdm_tagged_peek.c
- simple/scalable_ep.c
- streaming/rdm_atomic.c
The patch is intended to fix the following:
- Marks local functions as static functions and adds `void` to the argument list if the function argument list is empty.
- Pass NULL as a MR descriptor to the `fi_read`, `fi_write`, `fi_(t)send`, `fi_(t)senddata`, `fi_(t)recv`, `fi_(t)sendmsg`, `fi_(t)recvmsg` in case of a provider doesn't require `FI_MR_LOCAL`/`FI_LOCAL_MR` bit set.
The `ft_info_to_mr_access` function set flags as follows:
if the provider requires `FI_MR_LOCAL`/`FI_LOCAL_MR` bit set, the MR `FI_SEND`, `FI_RECV` (if the provider supports `FI_MSG | FI_TAGGED`) and `FI_READ`, `FI_WRITE`, `FI_REMOTE_READ`, `FI_REMOTE_WRITE` (if the provider supports `FI_RMA | FI_ATOMIC`) access flags are set.
if the provider doesn't require `FI_MR_LOCAL`/`FI_LOCAL_MR` bit set, the MR …
> common: Fix passing an invalid MR desc if the FI_MR_LOCAL/FI_LOCAL_MR bit isn't set

- .travis.yml
Travis CI has an issue where Mac OS builds are failing.
See https://github.com/travis-ci/travis-ci/issues/8703
Apparently it's an issue with rvm on Mac OS. Use the workaround
mentioned in the Github issue.
This patch can be reverted once the original issue is fixed.
> travis-ci: Add a workaround for a Travis CI Mac OS issue

- common/shared.c
- complex/ft_main.c
- include/shared.h
- man/fabtests.7.md
ubertest: Break excessively long help line and slight tweak to wording.
manual merge of OOB address exchange support, plus updates to simplify those changes.
> Ubertest cleanup, add support for OOB address exchange

- Makefile.am
- Add testing of rxm over sockets to make test.
> Add rxm provider to travis CI testing

- Makefile.am
Reverts ofiwg/fabtests#762
Still see failures in rxm over sockets sometimes. The tests somehow passed when the original PR was merged.
> Revert "Add rxm provider to travis CI testing"

- complex/ft_config.c
- complex/ft_endpoint.c
- complex/ft_msg.c
- complex/ft_test.c
-Added FI_DIRECTED_RECV as a supported constant capability
-Updated ubertest to support adding constant_caps to the test class in
progress
-Moved pre-posting recvs until after the remote addr is known allowing
for testing FI_DIRECTED_RECV
-Updated the value of ft_rx_ctrl.addr to be the same as ft_tx_ctrl.addr
given FI_DIRECTED_RECV is requested when posting recvs.
-Only affects unconnected endpoint tests, connected endpoint tests are unaffected
> complex/ubertest: Updated Ubertest to support testing FI_DIRECTED_RECV

- scripts/runfabtests.cmd
Edit runfabtests.cmd script to use 'rem' instead of '::'
Using the empty label '::' comment scheme is very error prone
and is indeed causing some sort of error for the unit tests.
This commit edits the script to use the less-error prone
rem command for comments.
Signed-off-by: Erik Paulson <erik.r.paulson@intel.com>
> Fix syntax errors in batch script

- complex/fabtest.h
- complex/ft_config.c
- complex/ft_main.c
- complex/ft_msg.c
- complex/ft_test.c
- add mr_mode to config file (one per test set)
- add peer_mr_addr field to mr_ctrl and exchange virtual addresses if mr_mode = FI_MR_VIRT_ADDR
- add peer_mr_addr to all RMA and atomic calls (and fix line lengths)
- verified working on shared memory provider which requires MR_VIRT_ADDR
> complex/fi_ubertest: mr_mode support

- complex/fabtest.h
- complex/ft_comp.c
- complex/ft_config.c
- complex/ft_main.c
- complex/ft_msg.c
-Added support for testing that a given provider fully supports the
options of selectively generating completion events.
-Added new flag categories for the test_config:
-rx_cq_bind_flags -> allows for passing FI_SELECTIVE_COMPLETION
to rx cq_bind.
-tx_cq_bind_flags -> allows for passing FI_SELECTIVE_COMPLETION
to tx cq_bind.
-rx_op_flags -> allows for setting FI_COMPLETION in the
rx_op_flags on the endpoints.
-tx_op_flags -> allows for setting FI_COMPLETION in the
tx_op_flags on the endpoints.
-Added support for FI_COMPLETION msg_flag for use in *msg functions.
-Added new functions ft_get_tx_cq_completion & ft_get_rx_cq_completion
which check the current test case to test if a tx/rx completion
event is expected.
-Added setting the tx/rx attribute flags based on the tx/rx op_flags
set for …
> complex/ubertest: Support for testing FI_SELECTIVE_COMPLETION

- benchmarks/dgram_pingpong.c
Commit a84977486 seems to have broken the FI_MSG_PREFIX support. Make
sure not to overwrite the previous mode bits set when adding FI_CONTEXT
support.
> dgram_pingpong.c: Fix FI_MSG_PREFIX support.

- complex/fabtest.h
- complex/ft_config.c
- complex/ft_domain.c
- complex/ft_msg.c
- complex/ft_test.c
- complex: Fix incorrect mem desc reference for transmit buffers (cc: v1.5.x)
- complex: Fix remote memory addr in RMA sync
- complex: Fix check for local MR mode and also pass correct access flags (cc: v1.5.x)
- complex: Add support for handling FI_MR_PROV_KEY, FI_MR_LOCAL, FI_MR_ALLOCATED
> Updates to fi_ubertest

- complex/ft_comp.c
-With the current FT_COMP_ALL at completion time the cntr records the
number of completions into the tx/rx credits.
-After reaching the threshold in the counter the CQ is called, however
the tx/rx credits are not reset such that the CQ ends up returning
with a success before reading or waiting for all the CQ events to fire.
-This issue is fixed by resetting the tx/rx credits after the counter
completes such that the CQ correctly reads all the events before
returning successfully.
> complex/ft_comp: Fix FT_COMP_ALL to reset credits for CQ read

- unit/getinfo_test.c
The original code had an issue if FI_PROVIDER was not in the user
provided environment. The reset code would set the FI_PROVIDER value to
the string "(null)" which would cause providers to be skipped when
trying to run a limited subset of the tests (by commenting out the no
hint tests). Instead of fixing the bug, this PR removes the reset
altogether. The reset is not effective because libfabric creates the
filter at library initialization time (first call right after the test
exports FI_PROVIDER). The rest of the tests will be setting the provider
name in the hints anyway.
> getinfo_test.c: Remove reset of FI_PROVIDER.

- Makefile.am
- common/shared.c
- complex/ft_msg.c
- complex/ft_test.c
- test_configs/shm/all.test
- enable shared memory provider by altering some progress calls (provider relies on peer progress and currently only enabled with manual progress)
- enable ubertest for shared memory provider testing by adding config files
- only set peer_mr_key during exchange_addr_key if FI_MR_PROV_KEY set
> common/shared.c, complex/ubertest, test_configs/shm : enable shared memory provider

- simple/rdm_rma_simple.c
- simple/rdm_rma_trigger.c
The tests set mr_mode to say that they support OFI_MR_BASIC_MAP,
but assume the key is a known value and that the remote address
is zero. Add ft_exchange_keys() call to exchange key and address,
bump number of counts to wait for. Delete confusing and
overwritten setting of mr_mode to FI_MR_SCALABLE. Fix minor typo
in help messages.
> simple/rdm_rma_*.c: Support OFI_MR_BASIC_MAP correctly

- simple/multi_mr.c
Check for NULL pointers in free_mr_res() before calling fi_close().
> simple/multi_mr.c: Don't segfault if fi_mr_bind() unimplemented.

- test_configs/ofi_rxm/ofi_rxm.exclude
This patch removes `rdm_multi_recv` test from RxM provider's exclude list
Please,  merge this patch when ofiwg/libfabric#3742 will be got merged
> config/rxm: Remove rdm_multi_recv test from exclude list

- streaming/rdm_atomic.c
If a provider requires FI_MR_LOCAL, then the three registered
buffers need different permissions. The first buffer is used for
send/recv and local/remote RMA, so it is easier to give it all
permissions. If the results buffer is written by hardware, it
needs FI_READ for the local HCA and, possibly, FI_REMOTE_WRITE
for the remote HCA; similarly the compare buffer needs FI_WRITE
for local and FI_REMOTE_READ for remote. I don't know of a fabric
that would actually access the results/compare data remotely ---
or with hardware for that matter --- but I'm leaving the
possibility open.
> streaming/rdm_atomic.c: Fix access flags on buffers

- test_configs/ofi_rxm/ofi_rxm.exclude
This patch removes `rdm_cntr_pingpong` test from RxM provider's exclude list
Please,  merge this patch when ofiwg/libfabric#3744 will be got merged
> config/rxm: Remove rdm_cntr_pingpong test from exclude list

- Makefile.am
- common/shared.c
- include/shared.h
- simple/av_xfer.c
MPI recently hit into an issue dealing with AV removal breaking communication between peers.  To avoid a similar situation in the future, this adds a new test to fabtests to validate proper behavior by the providers.  The test currently executes two separate test situations in a loop, with each loop creating and destroying all fabric resources.  To support that 3 smaller additional patches are added to handle re-initialization of test variables and OOB synchronization.
The sockets provider passes both of these test cases, but I did not validate other providers.  The test has not yet been added to the runfabtests script.  Comments in the code describe how a third test case can be constructed, but I have not had time to complete that.
> AV insertion/removal test with data transfers

- scripts/runfabtests.sh
Some providers do not support localhost addressing.
This fixes #758.
> runfabtests.sh. Pass addresses to getinfo_test.

- common/shared.c
- include/windows/unistd.h
- simple/av_xfer.c
Connecting out of band sockets for address exchange ends up
impacting providers that use an internal name service for
address resolution (mostly done in order to support fabtests).
Because the OOB connection is occuring at the start of any
test that uses it, it halts program execution until the OOB
connection completes.  This causes an issue that the provider
name service cannot start and register local addresses until
both the server and client apps are running.  This ends up
creating a race condition where the client may attempt to
contact the name server prior to it running or having any
addresses registered to it.
The simplest fix is to defer the connection of the OOB socket
until right before it is needed for communication.
> common: Move initialization of OOB socket

- common/shared.c
- include/shared.h
- streaming/rdm_atomic.c
- test_configs/shm/verify.test
- move atomic calls in streaming/fi_rdm_atomic test to common code (modeled after rma_opcodes) to use FT_POST function, enabling manual progress support needed for shm provider
- add test_config combinations in shm/all.test to test with and without MR_VIRT_ADDR (to test both shm protocols)
- add shm/verify.test for unit testing and for use with -t verify option in runfabtests.sh
> streaming/fi_rdm_atomic, test_configs/shm: various shm testing updates

- Makefile.am
- test_configs/shm/verify.test
- add verify.test script to Makefile
- also add quick test flag to verification tests because it takes way too long to verify 10k iterations of 3000 tests
> Makefile.am: add test_config/shm/verify.test

- common/shared.c
Turn datatype_to_size into an array and check for an invalid datatype
Also update copyright year
> common/shared.c: coverity fix

- common/shared.c
We can't call fi_cntr_wait() unless the counter has been configured with a wait object.  This fixes errors running over the ofi_rxm provider.
> Properly handle trying to wait on counters when wait support isn't requested.

- .gitattributes
- scripts/runfabtests.cmd
These tests will be removed by another patch.  Remove the comments
referencing these tests.
Signed-off-by: Hefty <sean.hefty@intel.com>
> windows: Remove reference to ported tests

- unit/getinfo_test.c
When provider name is something like "verbs;ofi_rxm", core_name when
passed as arg to snprintf would be "verbs;ofi_rxm" instead of just "verbs"
which is what is expected.
> unit: dup core provider name so that we pass the right string to snprintf

- unit/getinfo_test.c
The msg_ordering_bit and mr_mode tests should continue to
the next loop when fi_getinfo returns ENODATA.
> getinfo_test: Skip when fi_getinfo returns FI_ENODATA

- .appveyor.yml
- .gitignore
- Makefile.am
- include/shared.h
- test_configs/ofi_rxd/udp.test
- ubertest/config.c
- ubertest/cq.c
- ubertest/fabtest.h
- ubertest/test_ctrl.c
- ubertest/uber.c
common:
- on CQ or EQ error, report cq_entry.err, not cq_entry.prov_errno
ubertest:
- fix progress bug
- add manual progress config option
- add manual progress sync support to continue to progress
- add UDP;ofi_rxd test_config
.gitignore
- remove old tests and update test names
> ubertest, common: fix error reporting, progress updates, add UDP;ofi_rxd, and update gitignore

- test_configs/sockets/complete.test
- ubertest/config.c
- ubertest/cq.c
- ubertest/fabtest.h
- ubertest/test_ctrl.c
- ubertest/uber.c
- ubertest/xfer.c
Various ubertest updates to fix and test all completion scenarios:
- print/track skipped tests
- add bind/op flags to test info printing
- properly check for expected tx and rx completions
- make sure all completion scenarios are properly accounted for, especially with the use of cntrs/cqs
- manage all SELECTIVE_COMPLETION scenarios properly and use sync messages when necessary
- add credit asserts to ensure we don't find too many completions or improperly count completions
- add SELECTIVE_COMPLETION configs to sockets/complete.test (which tracks all combinations)
See individual commits for more information.
sockets/complete.test, sockets/verify.test, sockets/quick.test all passing
sockets/all.test hanging but is hanging without these patches as well - still investigating
> ubertest: completion updates

- common/shared.c
- functional/cm_data.c
- functional/msg_sockets.c
- functional/shared_ctx.c
- functional/unexpected_msg.c
- include/shared.h
- scripts/runfabtests.cmd
- ubertest/uber.c
If a source address is specified, pass it into the OOB connection
setup.  This allows selecting an IPv6 address for the source address.
This is a peer PR to https://github.com/ofiwg/libfabric/pull/4227
> shared: Support IPv6 for OOB connections

- benchmarks/dgram_pingpong.c
- benchmarks/msg_bw.c
- benchmarks/msg_pingpong.c
- benchmarks/rdm_cntr_pingpong.c
- benchmarks/rdm_pingpong.c
- benchmarks/rdm_tagged_bw.c
- benchmarks/rdm_tagged_pingpong.c
- benchmarks/rma_bw.c
The benchmarks are single threaded and can make use of provider
optimizations if we specify the right threading model.
> benchmarks: Use FI_THREAD_DOMAIN

- unit/eq_test.c
We can't arbitrarily set all mode bits to one, since we don't
know what future mode bits may require.
> eq_test: Set mode bits explicitly

- common/shared.c
The libfabric man page (fi_msg.3) recommends that application check for
completions on EAGAIN from transmit and receive operations. So don't skip it
just because a provider supports auto progress.
> common: don't skip CQ read on EAGAIN for auto progress
