ofiwg/fabtests

Makefile.am, simple/rdm_multi_recv.c
This is a merge of commits that add the RDM example
=> Add RDM example using MULTI_RECV feature

simple/rdm_atomic.c
=> rdm_atomnic: Cleanups to simplify code

common/shared.c, include/shared.h, simple/msg_pingpong.c, simple/msg_rma.c, simple/rdm_atomic.c, simple/rdm_cntr_pingpong.c, simple/rdm_inject_pingpong.c, simple/rdm_pingpong.c, simple/rdm_rma.c, simple/rdm_tagged_pingpong.c, simple/ud_pingpong.c
=> fix init_test() string handling

COPYING, common/shared.c, include/shared.h, ported/libibverbs/rc_pingpong.c, simple/imm_data.c, simple/info.c, simple/msg_pingpong.c, simple/msg_rma.c, simple/poll.c, simple/rdm_atomic.c, simple/rdm_rma.c
@shefty Can you quick sanity check this (trivial) patch?
=> license: remove "OpenIB.org" from the BSD license description

simple/ud_pingpong.c
Consistent with rdm_pingpong and msg_pingpong tests now.
=> Update ud_pingpong test with correct handling of dst_addr and src_addr.

Makefile.am, simple/scalable_ep.c
Added an example for scalable endpoints and added more comments to the simple examples to improve readability.
=> Scalable endpoints example & comments

common/shared.c, ported/libibverbs/rc_pingpong.c, simple/dgram.c, simple/imm_data.c, simple/msg.c, simple/msg_pingpong.c, simple/msg_rma.c, simple/poll.c, simple/rdm.c, simple/rdm_atomic.c, simple/rdm_cntr_pingpong.c, simple/rdm_inject_pingpong.c, simple/rdm_multi_recv.c, simple/rdm_pingpong.c, simple/rdm_rma.c, simple/rdm_rma_simple.c, simple/rdm_tagged_pingpong.c, simple/rdm_tagged_search.c, simple/scalable_ep.c, simple/ud_pingpong.c, unit/av_test.c
This commit is needed to deal with the removal of fi_bind() in
libfabric:
https://github.com/ofiwg/libfabric/pull/522
=> stop using fi_bind()

include/shared.h, simple/msg_pingpong.c, simple/rdm_cntr_pingpong.c, simple/rdm_inject_pingpong.c, simple/rdm_pingpong.c, simple/rdm_tagged_pingpong.c, simple/ud_pingpong.c
Use FI_* printing and debug macros, make help output pretty, add option to print input hints and version info.
=> Clean up msg_pingpong

.gitignore, Makefile.am, configure.ac, fabtests.spec.in
Fixed 'make dist' failure on fabtests and added spec file for fabtests. Tested the creation and installation of the rpm package.
=> Fixed Makefile issues and added a spec file to generate RPM for fabtests

Makefile.am, simple/rdm_shared_ctx.c
simple: Add an example for shared contexts.
=> simple: Add an example for shared contexts.

simple/scalable_ep.c
Update to match change to libfabric.
=> Replace fid_sep with fid_ep

common/shared.c, simple/dgram_waitset.c, simple/imm_data.c, simple/msg_pingpong.c, simple/msg_rma.c, simple/poll.c, simple/rdm_atomic.c, simple/rdm_cntr_pingpong.c, simple/rdm_inject_pingpong.c, simple/rdm_multi_recv.c, simple/rdm_pingpong.c, simple/rdm_rma.c, simple/rdm_shared_ctx.c, simple/rdm_tagged_pingpong.c, simple/rdm_tagged_search.c, simple/scalable_ep.c, simple/ud_pingpong.c
=> Move debug output on error from callers into ft_getsrcaddr.

simple/rdm_rma_simple.c
- Use counters instead of completion queues in rdm_rma_simple.c so as to
enable server get completions for incoming RMA reads/writes.
- Fix warning in msg_rma.c for unused variable.
=> simple: Replace CQ with counter + fix warning.

Makefile.am, ported/librdmacm/cmatose.c
=> ported/cmatose: Port 'comatose' example app

common/shared.c
=> Fix a typo in usage info text

common/shared.c, include/shared.h, scripts/ft_runall, simple/cq_data.c, simple/dgram.c, simple/dgram_waitset.c, simple/msg.c, simple/msg_pingpong.c, simple/msg_rma.c, simple/poll.c, simple/rdm.c, simple/rdm_atomic.c, simple/rdm_cntr_pingpong.c, simple/rdm_inject_pingpong.c, simple/rdm_multi_recv.c, simple/rdm_pingpong.c, simple/rdm_rma.c, simple/rdm_rma_simple.c, simple/rdm_shared_ctx.c, simple/rdm_tagged_pingpong.c, simple/rdm_tagged_search.c, simple/scalable_ep.c, simple/ud_pingpong.c, unit/av_test.c, unit/size_left_test.c
I also added an incredibly lame script that I use to test whether the fabtests will all run in loopback mode, just to ensure that they're not completely broken.  The script can be updated to take args, but I just wanted _something_.
Removed some unnecessary print statements that some of the tests display.
=> Update to support av_type addition to domain_attr

simple/rdm_atomic.c, simple/rdm_multi_recv.c
=> Add missing machine-readable printing output capability.

.gitignore
=> Add tests under ported and complex subdirectories to gitignore.

common/shared.c, include/shared.h, ported/libibverbs/rc_pingpong.c, ported/librdmacm/cmatose.c, simple/cq_data.c, unit/av_test.c, unit/dom_test.c, unit/eq_test.c, unit/size_left_test.c
- Fix a race condition in cq_dtata.
- Make option uniform across all tests
If these changes look fine, I shall update other examples in simple/.
=> Make test options uniform

man/fabtests.7.md
Started putting content for fabtests manpage. @shefty @a-ilango @pmmccorm, can you please take a look if it's something we can start with? I focused on how people can run simple tests.
=> Adding content for manpage

man/fabtests.7.md
Fixed some typos in the man page.
=> Fixed typos

unit/av_test.c
Fix to address av_test fail issue discussed #195 
=> Modified av_test to have bad/invalid address as an option

common/shared.c, include/shared.h, ported/libibverbs/rc_pingpong.c, ported/librdmacm/cmatose.c, simple/dgram.c, simple/dgram_waitset.c, simple/info.c, simple/msg.c, simple/rdm.c, simple/rdm_rma_simple.c, simple/rdm_shared_ctx.c, simple/rdm_tagged_search.c, simple/scalable_ep.c
This is a follow up to PR #189. Updated the rest of the simple examples to use addressing and info options.
=> Update other simple and ported examples to use the addressing and fabric options

.gitignore, Makefile.am, common/shared.c, include/shared.h, pingpong/msg_pingpong.c, pingpong/rdm_cntr_pingpong.c, pingpong/rdm_inject_pingpong.c, pingpong/rdm_pingpong.c, pingpong/rdm_tagged_pingpong.c, pingpong/ud_pingpong.c, simple/cq_data.c, simple/dgram.c, simple/dgram_waitset.c, simple/info.c, simple/msg.c, simple/poll.c, simple/rdm.c, simple/rdm_rma_simple.c, simple/rdm_shared_ctx.c, simple/rdm_tagged_search.c, simple/scalable_ep.c, streaming/msg_rma.c, streaming/rdm_atomic.c, streaming/rdm_multi_recv.c, streaming/rdm_rma.c
Move all tests which print performance numbers.
=> Move pingpong tests into their own directory.

scripts/runFabtests.sh, simple/msg_epoll.c
- Added -s option to the command that starts server and adjusted the timeout for quick tests
- Modified msg_epoll options so that it matches with the rest of the simple tests
=> Minor modifications to runFabtests.sh and msg_epoll

complex/fabtest.h, complex/ft_msg.c, complex/ft_test.c
Signed-off-by: Charles J Archer <charles.j.archer@intel.com>
=> Add uni-directional bandwidth test

scripts/runfabtests.sh
Check that required positional args are there.
Different timeouts for quick vs other tests.
Improved help output.
Parse test output like:
```
./scripts/runfabtests.sh -v -t quick,simple -p $HOME/local/bin  sockets localhost localhost | ./scripts/parseyaml.py
{'fi_cmatose -f sockets': 'Pass',
'fi_cq_data -f sockets': 'Fail',
'fi_dgram -f sockets': 'Pass',
'fi_dgram_waitset -f sockets': 'Pass',
'fi_msg -f sockets': 'Pass',
'fi_msg_epoll -f sockets': 'Pass',
'fi_msg_pingpong -I 5 -f sockets': 'Pass',
'fi_msg_rma -o read -I 5 -f sockets': 'Pass',
'fi_msg_rma -o write -I 5 -f sockets': 'Pass',
'fi_msg_rma -o writedata -I 5 -f sockets': 'Pass',
'fi_poll -f sockets': 'Pass',
'fi_rc_pingpong -n 5 -f sockets': 'Pass',
'fi_rdm -f sockets': 'Pass',
'fi_rdm_atomic -I 5 -o all -f sockets': 'Pass', …
```
=> Various small fixes for runfabtests.sh.

simple/msg.c
=> Trivial cleanup in msg.c

scripts/runfabtests.sh
- The idea of 'quick' test option was to verify all the tests with small number of iterations. So added unit and simple tests in quick option and made "quick" test as the default test option.
- Removed 'quick' from 'all' test option since it already runs the standard tests with all msg sizes.
- Added missing fi_info in unit tests. It's in simple category but matches with unit test running structure.
- Increased timeout values as fi_rdm_atomic can take longer than 60s (it runs 5 atomic operations for all msg sizes)
@pmmccorm, can you please take a look?
=> Minor modifications and cleanups in runfabtests.sh

scripts/parseyaml.py
Usage: parseyaml.py [options]
fabtests yaml parsing utility
Options:
-h, --help  show this help message and exit
-d          Subtract a from b and print the results
-v          Prety-print given yaml stream and exit
Use like:
parseyaml.py -d before.y after.y
Where before.y and after.y are output from the -m switch of
the pingpong/streaming tests.
Creates output like:
```
./pingpong/fi_msg_rma -m localhost :
xfer_size:  64 , Gb/sec: -0.001167 , usec/xfer: +0.002640
xfer_size:  96 , Gb/sec: -0.008784 , usec/xfer: +0.038680
xfer_size:  192 , Gb/sec: -0.020272 , usec/xfer: +0.050260
xfer_size:  4096 , Gb/sec: +0.007359 , usec/xfer: -0.007500
xfer_size:  65536 , Gb/sec: +0.025987 , usec/xfer: -0.103001
xfer_size:  1048576 , Gb/sec: +0.020773 , usec/xfer: -1.280029
```
Signed-off-by: pmmccorm …
=> Update parseyaml script with diff support:

unit/av_test.c
=> Update asynchronous AV insertions to check for 0 on success

unit/av_test.c
- Fixed return value in error case to be consistent with other tests
- Set addr_format to FI_SOCKADDR as the test is based on sockaddr which allows the test to gracefully exits for providers that doesn't this addressing format.
=> unit/fi_av_test: Fixed return values and minor cleanup

autogen.sh
=> autogen.sh: mkdir config if the config directory does not already exist

common/shared.c, include/shared.h, pingpong/msg_pingpong.c
Added call to these functions in msg_pingpong.
Signed-off-by: Prankur Gupta <prankgup@cisco.com>
@goodell : Please review
=> Including Data Integrity Test functions

unit/av_test.c
=> fi_av_test: fix arg parsing + usage msg

scripts/toCSV.py
Call like:
runfabtests.sh ... | toCSV.py
=> Add simple script to convert runfabtests.sh output to CSV.

pingpong/ud_pingpong.c
Similar to b79d536, add a timeout in the server side handshake.
@bturrubiates @goodell Please review.
=> ud_pingpong: add timeout in server_connect(), too

pingpong/ud_pingpong.c
=> ud_pingpong.c: Add help string for timeout (-t) argument.

common/shared.c
providers can then decide what call to use in order to
get remote or local address.
==
This is a much simplified version of #271. #271 was split into #289, #287, #288.
I gave up on the parts that were simply changing src_addr, dst_addr to src_node, dst_node etc. Those changes caused too much noise.
=> use fi_getinfo instead of getaddrinfo

pingpong/ud_pingpong.c
This mirrors ofiwg/libfabric#1133.
=> RFC: ud_pingpong.c: Use updated FI_MSG_PREFIX behavior.

scripts/runfabtests.sh
=> Fix runfabtests.sh script to correctly interpret host and client args

Makefile.am, scripts/runfabtests.sh, simple/rdm_rma_trigger.c
=> Add example for Triggered RMA write operation

complex/ft_config.c
Fix for #314. Untested but it should hopefully fix the warning. @shefty
=> complex/ft_config: Fix -Wunused-result warning

simple/msg_sockets.c
Fix:
simple/msg_sockets.c: In function ‘check_address’:
simple/msg_sockets.c:71: warning: dereferencing pointer ‘tmp.27’ does break strict-aliasing rules
simple/msg_sockets.c:70: warning: dereferencing pointer ‘tmp.27’ does break strict-aliasing rules
simple/msg_sockets.c:135: note: initialized from here
by using union for socket addresses.  Update all occurrances of
sockaddr_storage to use the new union.
=> msg_socket: Fix strict aliasing build warning

common/shared.c, complex/ft_test.c, include/shared.h, pingpong/msg_pingpong.c, pingpong/rdm_cntr_pingpong.c, pingpong/rdm_inject_pingpong.c, pingpong/rdm_pingpong.c, pingpong/rdm_tagged_pingpong.c, pingpong/ud_pingpong.c, ported/librdmacm/cmatose.c, simple/cq_data.c, simple/dgram.c, simple/dgram_waitset.c, simple/msg.c, simple/msg_epoll.c, simple/msg_sockets.c, simple/poll.c, simple/rdm.c, simple/rdm_rma_simple.c, simple/rdm_rma_trigger.c, simple/rdm_shared_ctx.c, simple/rdm_tagged_peek.c, simple/scalable_ep.c, streaming/msg_rma.c, streaming/rdm_atomic.c, streaming/rdm_multi_recv.c, streaming/rdm_rma.c, unit/av_test.c, unit/eq_test.c, unit/size_left_test.c
Create a shared routine to cleanup all fabric resources.
=> Provide common cleanup routine

configure.ac
=> configure.ac: v1.1.0 has been released; bump to v1.2.0

pingpong/ud_pingpong.c
=> ud_pingpong.c: Post recv on both client and server side.

common/shared.c, include/shared.h, pingpong/msg_pingpong.c, pingpong/pingpong_shared.c, pingpong/rdm_inject_pingpong.c, pingpong/rdm_pingpong.c, pingpong/rdm_tagged_pingpong.c, pingpong/ud_pingpong.c, simple/cq_data.c, simple/dgram_waitset.c, simple/poll.c, simple/rdm_shared_ctx.c, simple/rdm_tagged_peek.c, simple/scalable_ep.c, streaming/msg_rma.c, streaming/rdm_atomic.c, streaming/rdm_multi_recv.c, streaming/rdm_rma.c
Create a single function to reduce duplicate code and avoid
calling the wrong function.
=> Merge wait_for_completion with wait_for_data_completion

common/shared.c
=> Fix ft_alloc_bufs to set tx_buf correctly

streaming/rdm_multi_recv.c
fi_rdm_multi_recv assumes that FI_MULTI_RECV completions
are always separate from data completions.  This is not
always the case, for example, the PSM provider reports
this as part of the last data completion.  Update the
app to test for this correctly.
Provide a broad cleanup of the code.
=> Cleanup and fix rdm_multi_recv completion handling

scripts/parseyaml.py
<code>parseyaml.py</code> reported the subtracted the values from two runs(run_b - run_a). The script is modified to report the regression percentage ((run_b-run_a)/run_a * 100).
@pmmccorm, @a-ilango can you please review?
=> Modified yaml output to percentage

pingpong/pingpong_shared.c
=> Added send/recv context required for psm provider

man/fabtests.7.md
=> Update man page to sync up with fabtests changes.

common/shared.c, include/shared.h, pingpong/msg_pingpong.c, pingpong/pingpong_shared.c, pingpong/pingpong_shared.h, pingpong/rdm_cntr_pingpong.c, pingpong/rdm_inject_pingpong.c, pingpong/rdm_pingpong.c, pingpong/rdm_tagged_pingpong.c, pingpong/ud_pingpong.c, simple/rdm_tagged_peek.c, streaming/msg_rma.c, streaming/rdm_atomic.c, streaming/rdm_multi_recv.c, streaming/rdm_rma.c
=> Revert "Use common code for message processing"

.travis.yml, Makefile.am
=> Add basic travis CI test script

.travis.yml
=> travis: Add support for clang

common/shared.c, include/shared.h, pingpong/msg_pingpong.c, simple/cq_data.c, simple/msg.c, simple/msg_epoll.c, simple/msg_sockets.c, streaming/msg_rma.c
=> Fix handling of port/service value.

scripts/runfabtests.sh
- Enable runfabtests to run tests on an interface different from
the one used to ssh into the test nodes.
- Print the command used to run the tests. Useful for debugging.
=> runfabtests: Add client and server interface options.

complex/ft_config.c, complex/ft_main.c
=> ft_config: Fix resource leak

.travis.yml, scripts/runfabtests.sh, simple/msg_epoll.c
This is a RFC for now, not sure how to kick off CI builds on non PR branches.
=> Re-enable OS X testing with Travis CI.

scripts/runfabtests.sh
- Fix timeout issue in runfabtests.sh (fixes #385)
- Minor cleanups
=> - Fix timeout issue in runfabtests.sh (fixes #385)

README, README.md
Rename markdown README and create a skeleton readme for inclusion
in the tarball.
=> Add libfabric Travis CI badge to Readme, update slightly.

common/shared.c, complex/ft_comm.c, include/shared.h, ported/libibverbs/rc_pingpong.c, ported/librdmacm/cmatose.c, simple/dgram.c, simple/dgram_waitset.c, simple/msg.c, simple/msg_epoll.c, simple/msg_sockets.c, simple/poll.c, simple/rdm.c, simple/rdm_shared_ctx.c, simple/scalable_ep.c, streaming/rdm_multi_recv.c
This should address #391. Error code sign would stay negative until the exit of the app when we change it to positive.
=> Use common code for av_insert + fix return code sign

common/shared.c, complex/fabtest.h, complex/ft_config.c, complex/ft_main.c, complex/ft_msg.c, complex/ft_test.c, complex/test_configs/sockets.json, complex/test_configs/verbs.json, include/shared.h, simple/cq_data.c
=> ubertest: Add inject option; retry send on EAGAIN

common/shared.c, include/shared.h
Signed-off-by: Paolo Inaudi <p91paul@gmail.com>
=> Enable using counters through command-line switch

complex/ft_main.c
The service option in config file would override
the command line dst_port option.
=> Add command line addressing options to fi_ubertest.

Makefile.am, common/shared.c, include/shared.h, simple/rdm_shared_av.c
Tested with @shantonu 's new PR #1651
=> Shared AV usage example

simple/rdm.c
Use ft_tx and ft_get_rx_comp to simplify code
=> ft_tx/ft_get_rx_comp cleanup

common/shared.c
=> Coverity-scan: Added a missing break statement

Makefile.am, complex/ft_main.c, scripts/runfabtests.sh
=> Revert "Added option to run fi_ubertest from runfabtests.sh"

README.md
Will submit one for Libfabric as well. 
@shefty @jsquyres 
=> Add information about configure options.

README.md
=> README.md: minor tweaks

benchmarks/ud_pingpong.c
At some point the changes in #336 were removed.
@shefty 
=> Add an extra recv to avoid failure in ft_finalize

common/shared.c
=> Handle the prefix case in ft_finalize

common/shared.c
The warmup iterations count was missing from the help display
=> add missing help line

benchmarks/msg_pingpong.c, benchmarks/rdm_pingpong.c, benchmarks/ud_pingpong.c
=> Check the return value of ft_finalize

common/shared.c
sysconf can return -1 on error, which will be passed into
posix_memalign.  This triggers a coverity warning.
Also fix build error on 32-bit systems casting tx_buf to
an integer of the wrong size, and warning that page_size may
be used uninitialized.
@sayantansur
=> shared: Fix use of page_size

Makefile.am, test_configs/usnic/all.test, test_configs/usnic/quick.test
=> Add ubertest configurations for usnic provider.

man/fabtests.7.md
- Updated outdated/new tests
- Added runfabtests.sh usage in example
- Fixed formatting and typo
@a-ilango @shefty 
=> Updated manpage with latest tests

scripts/runfabtests.sh, simple/rdm_shared_av.c
=> Provide default name for address vector if not provided on shared AV test.

unit/eq_test.c
- Catches a bug in the usnic provider that invalidly clears the FD on
peeks when using an FD wait object.
@shefty @jsquyres 
=> eq_test.c: Add tests for peek functionality

unit/eq_test.c
=> eq_test.c: Fix typo in error message.

common/shared.c, complex/ft_comp.c, complex/ft_config.c, complex/ft_domain.c, include/shared.h, ported/libibverbs/rc_pingpong.c, simple/msg.c, simple/msg_sockets.c, simple/rdm_rma_simple.c, simple/rdm_rma_trigger.c, streaming/msg_rma.c, streaming/rdm_atomic.c, streaming/rdm_multi_recv.c, streaming/rdm_rma.c
These are best viewed as individual patches. The last patch fixes #456
=> Several cleanups and bug fix for fabtests

Makefile.am, benchmarks/benchmark_shared.c, benchmarks/benchmark_shared.h, benchmarks/msg_pingpong.c, benchmarks/rdm_cntr_pingpong.c, benchmarks/rdm_tagged_bw.c, benchmarks/rdm_tagged_pingpong.c, benchmarks/ud_pingpong.c, common/shared.c, include/shared.h
Rename pingpong_shared.[ch] to benchmark_shared.[ch].
Also print out the messaging rate in Million transfers/sec.
=> benchmarks: add a bandwidth/message rate test

common/shared.c
=> Handle FI_TAGGED in ft_caps_to_mr_access.

common/shared.c, include/shared.h, simple/dgram.c, simple/msg.c, simple/msg_sockets.c, simple/rdm.c
Add new shared send/recv greeting function and make use of it in the simple tests.
@shefty @shantonu 
=> Unify send/recv function for simple tests.

complex/ft_test.c
- Add a weighted IOV formatting function that makes the size of each IOV
entry proportional to its position in the list.
- Add a reverse weighted IOV formatting function.
- Add a formatting function that assigns randomized weights to IOV
entries.
@shefty @goodell 
This is a rework of #474.
=> Add more formatting options that are randomly selected.

common/shared.c
@shefty 
Hopefully it's right this time. :+1: 
=> Fix size parameter given to strncpy.

common/shared.c, include/shared.h, simple/msg_epoll.c, simple/rdm_rma_simple.c, simple/rdm_rma_trigger.c, simple/rdm_shared_av.c
- Added a common function to check recv msg data
- Fixed tests where tx_buf/rx_buf was not properly used
@a-ilango 
=> Fixed simple tests to use the correct tx_buf/rx_buf for send/recv

scripts/runfabtests.sh
=> Don't run complex tests that are excluded using the -e option.

AUTHORS
=> Adding Cray names to AUTHORS.

common/shared.c, simple/msg_epoll.c
=> Defer fi_control until CQs have been bound.

configure.ac
=> configure.ac: bump to 1.3.0rc2

configure.ac
=> configure.ac: bump to v1.3.0rc3

configure.ac
=> configure.ac: bump version to v1.3.0

configure.ac
=> configure.ac: bump to v1.3.1a1

.gitignore
Signed-off-by: Paolo Inaudi <p91paul@gmail.com>
=> Wildcard ignore (benchmarks/fi_ud_pingpong is currently missing)

common/shared.c
Apply comments from PR https://github.com/ofiwg/fabtests/pull/494
@shefty 
Signed-off-by:Evgeny Leksikov <evgeny.leksikov@intel.com>
=> Remove check for FI_CONTEXT mode in ft_finalize

common/shared.c
All tests that use the common code should now handle FI_EAGAIN.
=> common: Handle -FI_EAGAIN in send/recv functions.

simple/cq_data.c, simple/msg.c, simple/msg_epoll.c
=> Use common functionality for connecting.

scripts/runfabtests.sh
- Added negative tests to <code>runfabtests.sh</code> that passes invalid server name
- Minor refactoring
Verified with sockets provider-
<code>Run command: fi_rdm -f sockets foo</code>
<code>Output: fi_getinfo(): common/shared.c:444, ret=-61 (No data available)</code>
@a-ilango, @bturrubiates  @hppritcha can you please check if runfabtests.sh runs fine with the negative tests with your providers?
=> runfabtests: Added negative unit tests to test invalid hostnames

include/shared.h
=> shared.h: make sure this declaration is "extern"

simple/msg_sockets.c, simple/scalable_ep.c
=> Fix tests that call fi_getname before calling fi_enable on an EP

scripts/runfabtests.sh
- Use Python to get errno numbers. Python is readily available on most
systems and there doesn't seem to be a better way to do this.
- Check for ENOSYS in unit/simple tests.
This fixes #548. 
@shantonu @jsquyres @a-ilango 
=> runfabtests.sh: Skip tests that return ENOSYS.

scripts/runfabtests.sh
Example output:
```
- name:   fi_dgram -f sockets
result: Pass
time:   2
server_cmd: /cray/css/users/sungeun/ofi-cray/devel/install-fabtests/bin//fi_dgram -f sockets -s 10.128.0.18
server_stdout: |
Waiting for message from client...
Data check OK
Received data from client: Hello from Client!
client_cmd: /cray/css/users/sungeun/ofi-cray/devel/install-fabtests/bin//fi_dgram -f sockets -s 10.128.0.20 10.128.0.18
client_stdout: |
Sending message...
Send completion received
```
Fixes #553 
@shantonu @shefty
=> Add complete command line used to run client/server in verbose mode output

unit/cq_test.c
Test that fi->domain_attr->cq_cnt CQs can be opened simultaneously. The
size used is based on the maximum usable value from the first test.
@shantonu @a-ilango @shefty 
I thought it might be useful to test creation of CQs up to the domain `cq_cnt` value. Thoughts?
=> unit/cq_test.c: Test simultaneous CQ creation

unit/cq_test.c
=> Small format string fix

benchmarks/rdm_tagged_bw.c, benchmarks/rma_bw.c, man/fabtests.7.md, streaming/msg.c, streaming/msg_rma.c, streaming/rdm_atomic.c, streaming/rdm_multi_recv.c
- Update manpage to reflect the current set of tests
- Update test usage to be consistent with the manpage
@a-ilango 
=> manpage: Update manpage and test usage

fabtests.spec.in
- Update tarball location to point to github
Fixes #534 
=> spec file: Update tarball location

simple/shared_ctx.c
- Current shared_ctx example expects FI_CONNREQ and FI_CONNECTED events
for each endpoint one after the other. But it is possible to get
these events out-of-order (eg. FI_CONNREQ of EP1 followed by
FI_CONNREQ of EP2). This patch handles out-of-order CM events.
=> shared_ctx: Handle out-of-order CM events

.travis.yml
=> build/travis: Apply work-around for travis failure on os x

configure.ac
=> configure: make a final rc: 1.4.0rc3

configure.ac
=> configure.ac: bump to v1.4.0

configure.ac
=> configure.ac: bump to v1.5.0a1

simple/scalable_ep.c
ft_alloc_active_res() opens an unnecessary endpoint with the same
port number as the scalable endpoint already opened. This causes
issues with the gni provider. Call ft_alloc_ep_res() instead.
Also, check data after transfer.
Signed-off-by: Chuck Fossen <chuckf@cray.com>
@shefty @hppritcha
=> Scalable test - do not open unnecessary endpoint.

configure.ac
=> configure.ac: bump version to v1.5.0a1

complex/fabtest.h, complex/ft_config.c, complex/ft_domain.c, complex/ft_main.c, complex/ft_msg.c, complex/ft_test.c, include/shared.h, test_configs/eq_cq.test, test_configs/lat_bw.test, test_configs/sockets/all.test, test_configs/sockets/quick.test, test_configs/udp/all.test, test_configs/udp/lat_bw.test, test_configs/udp/quick.test, test_configs/udp/simple.test, test_configs/usnic/all.test, test_configs/usnic/quick.test, test_configs/verbs/all.test
=> complex/fi_ubertest: enable bandwidth RMA write testing on EP_MSG type

streaming/rdm_atomic.c
Include test of domain fi_query_atomic call as part of test,
which can also verify the size of the atomic datatype.  Keep
the existing tests in place for compatibility.
As part of these changes, the test checks the return values
from the providers.  This highlighted an issue with the return
values from the socket provider. A fix to the socket provider has
been submitted, but until it is merged, this PR may fail.
=> rdm_atomic: Add test for query_atomic

complex/fabtest.h, complex/ft_domain.c, complex/ft_msg.c, complex/ft_test.c, test_configs/sockets/quick.test
Adds BW testing of RMA reads.
Adds latency testing of RMA reads and writes
=> complex/fi_ubertest: adds BW and latency testing for RMA operations

common/shared.c
Only test memory registration for buffers used by the access
types allowed by info->caps.
Check FI_MR_LOCAL in addition to FI_LOCAL_MR.
Signed-off-by Jerome Berryhill <Jerome.Berryhill@Intel.com>
=> modify access criteria for mr_test

Makefile.am, include/shared.h, simple/rdm_shared_av.c, simple/shared_ctx.c
- 	Update version requested to 1.4 
-	simple/rdm_shared_av: Require FI_SHARED_AV capability
-	simple/shared_ctx: Fix memory leak 
-	Add running test over rxm provider to make test
=> fabtests: Misc updates

complex/ft_main.c
=> complex/fi_ubertest: fix provider name mismatch

scripts/run_with_output.cmd, scripts/runfabtests.cmd
- scripts/runfabtests.cmd: main script
- scripts/run_with_output.cmd: helper script for creating process in background
=> win/build: added scripts to run fabtests

Makefile.am, common/shared.c, complex/ft_test.c, include/shared.h, simple/rdm_deferred_wq.c, streaming/rdm_atomic.c
New triggered ops test for experimental deferred work requests
=> simple/fi_rdm_triggeredOps: add deferred work test

common/shared.c
- added tag info on tag mismatch error message
Signed-off-by: Oblomov, Sergey <sergey.oblomov@intel.com>
=> common: better error message on tag mismatch

unit/getinfo_test.c
=> unit/getinfo: Fix OS X build (and all really), plus cosmestic changes

benchmarks/dgram_pingpong.c
=> dgram_pingpong.c: Add OFI_MR_BASIC_MAP to mr_mode

simple/multi_mr.c, simple/rdm.c, simple/rdm_deferred_wq.c, simple/rdm_multi_domain.c
@nrspruit Could you review the changes on `multi_mr.c`, `rdm_multi_domain.c`
@aingerson Could you review the changes on `rdm_deferred_wq.c`
@shefty Review changes to `rdm.c`
I reviewed the tests and determined what the modes should be based on usage, so may be incorrect.
=> Update modes for 1.5.

complex/ft_main.c, complex/ft_test.c, ported/libibverbs/rc_pingpong.c, simple/unexpected_msg.c
Updates to ubertest, unexpected_msg, and rc_pingpong
=> Fixes to coverity reported errors

benchmarks/benchmark_shared.c, common/shared.c, include/shared.h
=> Ensure prefix hint is respected for -k.

common/shared.c, include/shared.h, simple/multi_ep.c
This test still fails periodically in travis.  Add finalize
step to all endpoints under test and hope that fixes the hangs.
=> multi_ep: Enhance finalize processing across all EPs

simple/rdm_deferred_wq.c
=> simple/rdm_deferred_wq: a few bug fixes that were causing data mismatch

streaming/rdm_atomic.c
- Allow setting of datatype (the same as for operation types)
- Some code cleanups (reduce code duplication)
=> streaming/rdm_atomic: Allow setting of datatype

streaming/rdm_atomic.c
=> streamin/rdm: Fix one more warnings

common/shared.c
-Updated the common framework to always create and bind
TX/RX CQs to endpoints due to the requirement for
active endpoints to always have CQs bound
-Updated the common framework to track the FT_OPT_TX_CQ &
FT_OPT_RX_CQ options to determine if the test wishes
to track completions with the CQ instead of if the
txcq or rxcq pointers are NULL
Change-Id: I26f518d66fe4ce9ae8b27355bad1d2af610cb01a
=> common/shared: Fix to always create and bind TX/RX CQs

unit/cntr_test.c
-For providers that offload the cntr functionality to the HW it
is not guranteed that the counter value will be updated
right after the set/increment call is finished.
-To support providers such as this, a retry loop repeats
the cntr/cntrerr read calls to allow time for the HW
to update the counter values.
Change-Id: Ib5c720614bbeeb9f0637d8cb4ca8a974f34332b4
=> unit/cntr_test: Update cntr_test to retry check on cntr values

configure.ac
=> Update release number to v1.5.2a1

streaming/rdm_multi_recv.c
-Updated the fi_rdm_multi_recv test for support for testing FI_MULTI_RECV
with the fi_recvmsg API support in providers.
Change-Id: I904ccc667402c7ce28d2549ea30c2572c0a34ca5
=> streaming/rdm_multi_recv: Add fi_recvmsg testing in rdm_multi_recv

common/shared.c
=> shared: Fix resource leak in ft_init_oob()

complex/ft_main.c, complex/ft_test.c
- complex: Update logging to reflect correct default test
- complex: Fix missing fi_close for atomics MR
=> fi_ubertest bug fixes

unit/cq_test.c
This test will require fixes to the util CQ code and sockets provider in order to pass CI.  Those fixes have already been submitted as a PR.  Other providers that implement their own cq sread functionality should verify that they can work with this test as proposed, or if changes to the test or provider will be needed.
=> cq_test: Expand simple test to check fi_cq_signal

scripts/runfabtests.sh
@bturrubiates Does this look good for usnic?
Updates changes in PR: #807
=> Fix address passed to getinfo test

complex/ft_comp.c, complex/ft_test.c, test_configs/psm2/psm2.exclude
- fix missing check for FI_ATOMIC
- fix cleanup order to avoid race conditions 
- fix poll_time not getting updated due to lower precision
=> fi_ubertest: bug fixes

complex/ft_main.c
- complex: make server_ready non-static variable
- complex: make forking of process optional
@nrspruit The first patch in this PR modifies code that you added. Please review.
=> ubertest: make process fork optional

simple/poll.c
The fi_poll test attempts to check if a provider incorrectly reports
too many transmit or receive events from calling fi_poll().  However,
there is a race condition where a provider does the following:
if (value < last_read_value) {
last_read_value = value;
report counter;
}
The fi_poll test then adds this check:
if (tx_seq == fi_cntr_read(cntr))
tx_done = 1;
The issue is that the counter value can change between the provider
saving the last_read_value and the test reading it.  So when the test
adds a check:
if (tx_done)
report error;
when fi_poll() returns the counter again, the test fails.  However,
the provider is correctly returning the counter based on its last
read value.  The application must be able to handle fi_poll() returning
even if the counter value did not change from its …
=> poll: Fix race condition that can incorrectly report failure

unit/getinfo_test.c
=> unit: fix msg ordering check in getinfo test

common/shared.c
Sometimes completions may not be reported in order. rdm_tagged_bw will
fail when that occur, because it expect them in correct order. As it is
benchmark test it doesn't need strict tag validation. This changes
compare method to check if arrived tag is in range of window size.
Signed-off-by: Marcin Salnik <marcin.salnik@intel.com>
=> Change tag compare method for rdm_tagged_bw

Makefile.am, test_configs/osx.exclude, test_configs/tcp/tcp.exclude
Signed-off-by: Venkata Krishna Nimmagadda <venkata.krishna.nimmagadda@intel.com>
=> Makefile.am: adding tcp to CI testing

Makefile.am
Signed-off-by: Venkata Krishna Nimmagadda <venkata.krishna.nimmagadda@intel.com>
=> Makefile.am: add tcp.exclude as part of make install

unit/eq_test.c
eq_readerr_ret_eagain tests
Signed-off-by: aleksandra.justa <ajusta@gklab-125-155.igk.intel.com>
=> unit/eq_test.c: Create test for reading EQ eavail error
